# Staging resource patches
# Patches for the traefik deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik-system
spec:
  template:
    spec:
      containers:
      - name: traefik
        resources:
          limits:
            cpu: "750m"
            memory: "384Mi"
          requests:
            cpu: "75m"
            memory: "96Mi"
