apiVersion: v1
data:
    users_database.yml: ENC[AES256_GCM,data:8vK0tEtZUNPY4DA9aB/90hT5gDHe5d/xqyWlnGL7HvxNF/OFunmt5OlaZU7oJiCE1tytNC5p1GuHLf3VwS2a5DMJNWZy/+Dn8Smq1cgtyCC+757iW91Vk5e2TIOYXZMRlYHcYi5jNGBmL7MxXMIDzF/+iZ1WXe/nUcDwFTkAEXQuJLiva34DhxwvcC3E5VuvIu/sYZoxymPDQTXY5mP2aklShZc0o3Wp6tt77uoZTirBtkFTMcFXhKEa44nl9yJUId6IeJ6s8ZkZAlwfc1NWkT4uko61/2gHcYa5EH9i9fjQ9rFbWqB16Q5NWSq6XcHYxOI+QNoxwm/eOF6rHetPN5xRU76IiJBEs8MuFENBH+zSTwR5EVzK/SFxnHxavuOoZunLRH1pmwiyPIbZ3UChsBGZ2vnqBJxBPj26lw==,iv:+S7JvSRkjCKXEVLDYplBhPd7Q6emabNpgkNbuyJWnik=,tag:qubIl9OYRH3peWC2cLNdtA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authelia-users
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU2JCdzB2VmxBYXE1RlQ4
            cmxYSkdjL3FialJ2RnhTM2d2bzBkMWNsMVZnClFRSktsd3hSM3JxWkI3YWNYaDJE
            d1JYMWJsbjgzVW03YWxGcExYT1Ird0kKLS0tIHFKSFcreDJtS0lkNEZ3MlNWZGgz
            ZTBncnVOdXd3cDB4SjN3d25rMEt0WGMKNq4thyvAvox1UcuJGskr3KA6Ir+xpYSu
            o/33JXTLYe7DaztxGD8pD2TQ6hcs3e60SuHW1eq8aKX+38C1slCssw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:cnyYIvKLtLGEg8Fot8LYrZl7x+3Tzo58o+rTJF9I7/5X2r8sbgp3MnQVZ94LtRg/J6MzKVPegXyywiKTABmeJpFpWbzqnM1hZOfALdheZCB0AQHXnwPIAltslwkrM3NKcdQyov2qwhPFKuGglW28e7gddtCfamGDx19CxEbCw5A=,iv:/sjXulcKPCPK0xwDuZ9aUEqYrOy6sxA2JWtTqy8sCa4=,tag:Nk+IdQmF6MpWyjy5E3FjnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
