apiVersion: v1
data:
    jwt-secret: ENC[AES256_GCM,data:jdBbPCE3RQna3UhYt0W0TvSbprYmI2k1RZRdtyA6TjQwDxFIqB67FHbbHbQY8DTwKDDM4eAtN3ZqgCWuADZ8PBxawDjDoLFkwR2c/GUWBH4ulDA7DebFrod59UnuBWP/ECFIyud2alk5Gm1DnH+0fjLUb7MNegxLi+EPydi2L333JVW2tty1TZn+HfvrnWSYRseu2sxTtjzK7SzgjzL/Ca3e7r9fOCP8XD7Mmw==,iv:/JpOqKIPgKTmuralF2O2iyJKnZc8AvSPBps/qfcME9Y=,tag:Fd8/kTIho/E/30AxSEhIVw==,type:str]
    redis-password: ENC[AES256_GCM,data:/0yaizW/eh6HOXGoSgjXODFhRJ+GYwPwm3zMEDuhixIsEyEyklB8DTVobbY=,iv:pWrTPyHtua51aUPw82s80x4irBJtvZxf48Ics9katyc=,tag:Key5Z+lmCxib66CT3mE8jg==,type:str]
    session-secret: ENC[AES256_GCM,data:gVGh2wLweQXlhkdppNDpjszRiTZx3/PqQxPxDvkU4D1jMtaWDM8S+CZ8+fFdbAYN04V8iZi3FxDW1tXcFhki5ZwD0vywGdOFHLSl0RJV5CgIgFLRWHKBpdJ8huL1JBolQBuKqD6fcTTzfA3FovwhuaOqK929IWafIjAT+5uGODsVvvzpGobZtrMPvtrhNC3lTlMmb29KftaXjHJebKvAnC2smk/efkryZrLYDg==,iv:Xx1XJcsyxo0YzBUD8SNCZ+77Gsqo1id3aTWJwxX8lQ4=,tag:6/b/USWr35+SSdzLxNjYpw==,type:str]
    storage-encryption-key: ENC[AES256_GCM,data:C8+W0FhoPN4j7vtz81nWl2OEibKC/nk0daRVtLK3jzE5BovYy1KpK1PNJ7WVp8yBSl+NzFNVBAD7uOQwX5IoeCqnIkub7ccTceLboANS/bk3wAI+BC2sCAQw6JPm7PlsrfbaLx8/6uYgtqS52EoPjLS7GdCZHD8Nd1j0VQMAe9TO0yQRFplB2CMbUF+hx9LQQ9GfdJXnj5PRLqhBWLPiy25jUi9IHhmKkLhBkg==,iv:Z9i29uPuOKPIgHeY5C6dHJN3eXVHrqR5hTElkEtEkjk=,tag:Su5WjCpRaiaQfsujOFHRnQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authelia-secrets
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOFRESUljOVRjeURzR3k3
            OHRMT3NlTHBTQUdiQ1BHOFZWWjdEOWNpRXhzCkx0V0R0WE5iNzhaRmY1UER2a1VD
            bS9FKzV4UGcwRFFFeEFJUEI3VWtWQm8KLS0tIE9UM2lpNEcxUzVSelBDWVlRL0pn
            RlR0cmhLTlhFY1BqTlFIYXBxS0xBQTgKzk12u1OoVmtRF3HfDUu+jXBwpGQho2YS
            pcoV4rlnOkHwFgDNiUMQwK91Dw3NLHEFsDlcfONzrCczzkCWvlOrRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:JnngAbz8WMmqVcpTzc0d1Gxi9v3c4RJdK3pNYz881IlbWZ56o/j6WihKxml6rQG66TuDBopFfgL/QNi/WIGJnYuL4w4TW4um8e0czAHdM5p8tvlyDJVdCPD3UXIC+L8Bv3nRi4drxVronf9bWA9Iobcp/bdHB0/QPlwNx/dWijQ=,iv:C7VF/ma8+TcA0RFMbbwEuKlsbdVrz/cHmSx8bnEul70=,tag:+opdbu62wKW7u30U6lrQew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
