apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ieHXPDxqebOlS0Jaa80JFUwMzVxgZDGDuEDTwQQNPkxvoTjTolJfHbjUkFg=,iv:EGC+t47nwsxkeLzDpYH+Zn5T0YuVB3ZAw9vNgyuYVdk=,tag:mYgHWTmM7fdTIAhk7SydLg==,type:str]
    username: ENC[AES256_GCM,data:WztRJLmzrXQ=,iv:vN/qI11cPZSqerPXPE+2h/vF4fr2A7B0a+4sUAzlw4o=,tag:QHjtVJKuKCEPcqFChV9Z0Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authelia-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVXpmbmNrV2ppcXN4L0pX
            U3E2R3FjZks1bUN3VVk2VHh4am5KVnRodGlVCmt5Y0ZaejJSZlIzUXpybFNicnVo
            RmpNNXhvcmxxRFY2UkxCRyt1UGRESVkKLS0tIFY4VzNEbDYyZWROY3Q5dmJOUTl1
            c0JZL0RHMmlIVjRuTnErQWUwUDQ1TzgKlTCnAI+fRn+EDvH3iH54o2f4POk7ritN
            CnWxFvkslYlqPK8Bkb3VImHBRypHfCAs47+SRe4xzxUH9DxgUXRNNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:UnE4tPyAWA+OR5vLd+thyrPLs+l8COhqVk8jXBWGKzSC6MsiiKDUJRH+MTULOhPHUP/wf5Q42uc6702fh1+kIOcu3UCLk5vlAKmEWuLlrN02W1tnwn8wzakWErplTJ898AidogLMCz6JLalEerm8zlOE9kcwsKxzun9MhgxpSSo=,iv:GLP7rBlnLFKKHbaM4hJGRP5qr4fgRnLkTuUYABqiq3E=,tag:+38+VcvvBWzkf5JsE28qBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
