apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:hG0pRdPJC1KM9RrMoNUYY7kd4GQ6TMe5qmY/wZb2vmN3A9W1,iv:yPS0Mqea5BnzpT3+ytKWer015L596mwKqLhc4F5CgUI=,tag:uvhG9qXhOze2bQYDGsbyVg==,type:str]
    secret-key: ENC[AES256_GCM,data:AJDYb5taapnSWD2/o3YborUS5bnA6dwKhBN5MjUMjn/8gVj+D9BjzOI095pA+KFGsyXTPouqfXFpKYABsuiC5ZD5gVAXh596eojDbSph0RVtbTJp1LC0yw==,iv:ZPlob+8lJRAd95KPYNL5mS0ACbT9zGSMkUJbBWKTCak=,tag:BmTKDuCTYQssNWCtnBJt/Q==,type:str]
kind: Secret
metadata:
    name: backup-s3-credentials
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU2FnLzVLV2diYUQwcFBN
            U3J5N2M4QjRwbFVBTTRQVTVlcXdyVHZieEVZCmQ4R25STlJaUDRWWVNFQXgrZEJy
            a0I2VkVtQWQ0WURaTlFtallLQ0lVbTgKLS0tIGJQM0ZqR0VwS1p2YzBlMXJubHJ4
            YVZ3UlRGVFNSQjRQZEZoY25hdGhHRDQKWuI+JRTOfDAAYaZYjWI0Jh/zyP5jt+4r
            pJj/SLh507rIOcuujOyU9lw0DCSaqRW9YMFTAewnIhZ31zux2CPwkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T23:34:55Z"
    mac: ENC[AES256_GCM,data:DvNP7ELx+YPTKbmVw8A5JD4W9mg0m4TWG5G816h5y/qsHUXlQUuv/N+TIP5Y1G5WTdhkX6VlbQ428igEhDHXYbkxvkTLx0rgonIQea6Vr5kL2Hm4aXNYfqMqzPBgrh9ZvrpjU1sCn3fNUk1rTWftDuocXOauXvpTBdguh3E2mQo=,iv:Eadw2+ieNC3ksZQit3QmNUCGf3SOb5bk117Rtec3ke4=,tag:VGDUGQyfSdbCCLQke77utQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
