apiVersion: v1
data:
    password: ENC[AES256_GCM,data:SAtjmTaGG479Kunn7mElV5lQDGruaR2CwgQB6s00gnHlEzzPdg6XK2qF0Gc=,iv:hbAZwZD5R9lkFl+QFC6bp0U0JWpHRwMOJu0j1ktbNJk=,tag:l8KSsCiUhluD5q5NEjKYsQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: code-server-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1NjbHZKVFhHMVF1YmFu
            NG9ZeDdkcEZ0VCtwTVYrdmlSNkM1U2tYT3hNCnY4SWd3c2RCOFdwUktpQTAvcWNm
            cWxiaUNEN09HUWs0YksxZ2xNK04wVEUKLS0tIDN6c3d6bGcrazlva3c3eG1SK0F0
            ck1JTWlsMGIxdnhXZmlsQnh6djV5L3cKRa8sxsG/x2OPnRHdcUSVed+Evhpg+mij
            /yEl6jh6D5Kr+Or5CnhYWXHgWQaFYymoERDPds0OWhMIVyDo/eUdbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:75Fv8YxIbkoe/zXZjMSh3mHyfR7k9FKqaFxqEm0opZWY4Xt8kOGT6dUi1cgnN4U7UhqqJm3AtPHAzOAGeXIOvUkICQO1oEGwzMmpTnBb9NYXJY87c4SGzfO4Lpaj+uHb5k7JR3s5X3Mc9G2CxF3nd28xmfOHgFHzJmCUTUFkQ0g=,iv:Un7oD6OSx6e4D6LyGSl7CmDKcMgVab9pKhAHUNWpv34=,tag:FW0cI+qCJYDNwN12ueAeVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
