apiVersion: v1
data:
    bouncer-api-key: ENC[AES256_GCM,data:+C9Syjs8qkd7j0MhsW9If35S16EpIVblwYteEKhv7Z4c2iMKcvPFsHyOvdSKIdrEGAK/nIVuBPPU8CZq7C+GuRmMovE1Fg1H10o3g7bw3yK3ZPYj8kRSKw==,iv:6+j/WHcDY/3lAVn3HsaNCFH6TWwK3t1uJ2wBTii8ksE=,tag:9lcLEwSLuPPtm0M2Rfu2QA==,type:str]
    enroll-key: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: crowdsec-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHIxbUJUNEFvNUdjbmlD
            T0RvV3Blb1lNN0dzcXpLQmlVb3NhN1plZFZRCnY3RWc5aDFJaU9lYjVKNUR4cTdG
            Q2hOWlpsN2lvTkIvN1lOMDVPc2p6cEkKLS0tIGMvNFhXWjl1SjZOWS9hckF6YTFD
            d2Y0S0liYVFZdWhKcE9weWdGQTdnaDgKxRzElNn6AJKcVO6eOunhHp8M2tsEWgQR
            9NfiO9H/fko5VZ2JN1FkK/LK1vb19Ybt/WNjV4NARQatvoWcnZQolA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:1Ww7yUldPy2sVUcXlfqWoct8MtUIvGQiPosO/upk+Qo9pIW9UjifAqjCJ/28L6y+z/nLEqZ946eY3Ps2z0Bgv9eHYvgB3Y3DpzAf5L7p3rKqBopMRXgof+CsIPaoSrOD7bbjPb63ZxCSTRDl7E4zH5GLq3cFbeY75il7wMwVI/A=,iv:ZkGVdmPLrWaVOj0IgtKVcdIMX4rNJuIAU5oQnOyQO70=,tag:wZaKytGr3sl3D+tW6XKoqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
