apiVersion: v1
data:
    database-url: ENC[AES256_GCM,data:I8isSt3Q0TnEb+mzOOKyD5qDtjgx69GqqwGGdjHXqOkXx3S3a5VcTT3ngE46fjQQDnB6HLEB0d/LmM0ivQaRn5hWdi4ePbHN58h1OZelrGjCziNgbx54woPHbMSntvjxwXg2NzpKKfrcRwb0BxDYjX5FdRY=,iv:+ERhux3o1eEZWqxpFU8ZEXOmASi2LrDxggRix4WQyd8=,tag:yjqWqqbpamIWsblkVJz49g==,type:str]
    db-password: ENC[AES256_GCM,data:9vOJ++JpAHm1hh45s21PyR6XrwREos/ZmC9AYh89AXqfTDcZjiPkKI+anvw=,iv:+Xadjb5kNVTpy3o8kTQUPsDhgv8LO6IC05jiVR8hdRI=,tag:zrXNDHCMvgYnX5Sxhiy4ww==,type:str]
    gitea-client-id: ENC[AES256_GCM,data:ETMwUQ8L/AqescGkUwak/5ClNvNGazRknicbeHBPNdG8uAHVOMVUh6RkeOg=,iv:zRmPyFaNk4Gl6BHYi2I8V2vNIY44jVtnwOQt1Qsyk8k=,tag:s0TfDSZM+rXoosBFlDgCOA==,type:str]
    gitea-client-secret: ENC[AES256_GCM,data:cyCiZuvxUflDXLRncfaasIr6xXw5y8EedrkwKVQR13R67TrIemUkGt0bJHmhovgKCDjy5LDClGKMguSl2u2LEQJ5pepzMwHcc7g/S0V9Vmb6MQrem4/GzW/gAzxBKMMwhfzCHT/H3mj9J4Vt1+VWMFiW+UwSYpdp1t+IBVzmZRiWb/Na9T1P5JHutTxAVdOiem05WePlQWprvHUMZAqupLC+Fo61loGXn4BvoQ==,iv:JuAWSajCtKu1oPbML0FU2RIX2jpz04P/+cI2Z5T0kpw=,tag:7dWTAghs4nLLi2Kcy2Pw3Q==,type:str]
    rpc-secret: ENC[AES256_GCM,data:D3ShAptOEtEPNxfyDC/BsRkSa3cPr5eXcXD3wtbsrSHzeEVE706bg4Xclka1TBof10Uztu6EAfnHb6ZCHUaM1VH24wqhtM/F9cbz/JDsqbK+KCVOuAzPXTaBdN8ZIBS9cFN2AruxRRKzJ2V8YsVod0PKA1+lqNqq3LlOhf80WgWO0DpIt++xISK0drBtegVxx5BCev88hdTlSpzvJVIJJh3FoSitb8HjVt9YzQ==,iv:BrlT2Bokp0RWATo5v+7o9aC8vRSZNBT/h0dxoUyFMIQ=,tag:VDuntcVR15hYvPF4IhYhuQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: drone-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR2xDTGxjb2trU2Zma2d6
            V0htM3JObnNHd0pJZDVudnFCTEZPMWtFbUhzCjVmNk0rSWxLUGZ6K0dyelRWVW02
            bkJ3ZU1QSGdNaURLOFpGajJzbHlsaW8KLS0tIEJHVmVXWVlvVC9vby9PQjNXREVm
            a0F1dHhNbEhNRVpKeDNJQXV5QXAwb1UK1Ejdr6D9MRwVeZ88LjLUyOjr4ZsKsM3/
            oG5C6xgJgwZnG3NNwwL5q9Q9SnRsZeZ7NDaYyaw2v+FK6ljDRBXhbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:HPdh/6j5SGZ10lVOjZaHnXFWE5elmVvQCKvo6irlhBcr1/cozN9m+RTcqjne+iWOhHtzvzMEKdV/HZKLpoJBbiY3scHsfJbsSoO8HYG9YGSeMwNJ6kNQU2x8kSvEkgfy7CgPLooJJ05i3UHpohOOnnsEy5zB4n3/1InkVvG39Cg=,iv:8ziO/z6EA6QM4YNd7456po15MdU0sFN2odCOLOpdo5U=,tag:ASwPttOqYsMmPuDO4cK3Dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
