apiVersion: v1
data:
    admin-token: ENC[AES256_GCM,data:AqwQEuysqaIyqJr0W/hzqsRoSQ3T5wFAGRyMnPPSeJfcCS6rQwy+wppC/6O9JBDHCHZBN6KOi1EzAZNXb25ZR+LsutSKdmVe7D9d0tHKma/N2valDdRTww==,iv:3r+wride1VsoITyEVi1W220rBhQq7CsG15rBkSRuk3Y=,tag:ywvXpaYBBQEspt8y9FX5eg==,type:str]
    metrics-token: ENC[AES256_GCM,data:pTu6QSuipzb7p7cJUgj9ZhrXZTc+dTb8PN7mHcSN8j+y91iM3XK098XQOZvi5NlKqMKB9JhVuIw4ns+gbOWB0HAyy51QGZRpY27GgwU5RXFmooQbtCwudw==,iv:hHkwOgSnIrS5bIfIbcNsFb6JGLSS4DeX+0rXJPLws4I=,tag:0WA2Hu0QpN2Xr0FsxsKiFA==,type:str]
    rpc-secret: ENC[AES256_GCM,data:G5g4ctq2mRsy3a/QB/Ll4cOQRevJ3C+ZyaO23q96gKBv6HGX0MVSfFGwelZegxoaUSEtLdsXr5jMBzHT2gNJrgyMT3Kg2qHIpbfJVDvkjwPbq9/Y4KO6xA==,iv:VcCzeVlzVOR0t5kDQWGOBTnXr0KvJ8XhJUHpK/AaoME=,tag:z8Ae1NGWFxpVlo0qMKg+xQ==,type:str]
kind: Secret
metadata:
    name: garage-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYnVlbks0NFllc1AyZzhl
            MU05Vlc0b3Y2QWJBOEl0Qng5UkxmR3ZJNmdFCmtwNzhlQldJZy9kRjg4TlErd0pP
            SVZ2MmdhUjcvcGVtS29VekRJMVhHWEEKLS0tIEdpTjVDRi90TnltODl6TG9TcXF6
            bmtFbytxOTRIMHhZZm85ZVJoMUxOeVkKaCAcohAMfN5HyDfp9bGIj8Z7fuyBf15k
            9efLFYB7xHPqH6pOHFXgJtWhSzdNUCwtHI332c1U4/wI2DM+3aI+SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T23:34:55Z"
    mac: ENC[AES256_GCM,data:wVdFV0bK5yUZhtmmd8WHH47N2DbdUNKqrB50KjFxnw6TOBiAKv8s95JDs0VlitPQRCaljzYZYJ+UnNioUpvvzW5cuoJR946pcPXk6Z3NEWXfo/eEurP+eJehMHgCr1aCQzQXCzJPqM3sbje7emucXHSayNP3y+UcRBkhu5MbgVg=,iv:MCkRdPN7KHzwEVIiBIQqUipncMQbcsPXPc/r4azmieo=,tag:XbOD6I2aQHy2b+gNEEPpYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
