apiVersion: v1
data:
    password: ENC[AES256_GCM,data:kfA3tq0M7L7iSiNzOfaeJMUHA6Ty0eG9HIcUyLFG+TR1MZaDYxXovtYxNtk=,iv:qmeXhiFVEikxOlyJOtkpW8JX3hSzbSErVxdJmLiVl4E=,tag:rQjb/bjUQtSV8PdDhW2J2g==,type:str]
    username: ENC[AES256_GCM,data:ZTgAZeTdeQo=,iv:rYXYZn9f8/5dbrjkeowqXVKkNP6Kgueo2bSOytGHtGA=,tag:OZwxMQ1GceiRQIcucONTwA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitea-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZG51VWpNRmhYK2dpWEZa
            YTZZTjNsTEo4TGxsRnh4dkJ6b09Hek0vZWd3ClZsQ04rVlo5YWg4N1lLdDg4T05G
            cVIrbEF2cE5ieWpwZngzS2tBeTZIMEEKLS0tIEc1Y1BzWmxYQjVpWXVxbkVDN3Y1
            MXBXNmY3UGNsZXoyWG1YbzNQaDJ0NUEK2wV0Btl4DrUyGubcmIVnX/MX1Hwi7YuK
            ARP0SaixZT14cSigVvzT1KsvdJkSAp4UP6sEGqbOH7+BDjVpMh+lPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:OpPD3tbf9+bXM+Dfe7Lx3iIzuB+dMdd9NgVpDuu+HGbSwJF+fKBpPobJ4Q+2b3eN3dr5ULk2lrbRSPj3i7Ge9j/eLto5N4D6mJJOFzV+lUQiMuy6Idu46ESgsCR9ePpeWYOA0XV6X387UUjnEfvryG6sQpWhIhBp7Mnb8TGZ5kw=,iv:f1J8zCsRMK4AiQZJcvzD3jI01FS2fnQNVNdaVWyaMr8=,tag:2Ut6duQztJDk+4z6++pmoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
