apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9LeGzfrnPLHNYCyPgy8LIcchyVi0MERTuSvnZ7Wc8+UO6fZtf0Ass3ZfvF4=,iv:hsaOXKXT5LJMbgrUkkGiXW1BsEcLQNsS5WirhrMEvQ8=,tag:1Tb3TIS6XQGnKft9grpVlQ==,type:str]
    username: ENC[AES256_GCM,data:uuI7E2CETeg=,iv:yGzPs2rCnsznLbRzTWAqOec7S7PXO0Y79iOW5+tqBRE=,tag:vg7hNiscDvYX4Dq8Dw2kWQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVW40VHQrcUN4dnZBbzNv
            VmpZdEIyNlNpeXppazE2WGR3UTIxMUpvQnhJCnBrSHlvMFdiUmhhMWpCdVlhejUy
            T24xMW1zb3lSUzlRdlc2bE02WVo4Z0kKLS0tIDFYMDVGNUpaMDhKOUljdnEvRWZj
            eE96M2V5ZTlkRGpFc3UyVjZRZkFFcW8Ks8IhhabACEZFuQhC0NCGPeqtZq+68Q3W
            RWHzVMVzul1cXEdMfoqaGZkuDOIOwo802EKWBrv69zrW3VX1olcbgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:O0AaUvkk8nYSL4umpzA1tv28GqLzEX9uHASTmTQpeBP/dsSER62GLapb+8zZ0FF6z9qzQZw2CPseA2woDGajydq/jUsDUnKPz5Ks61A4NjpqvSNTHeTURGImAnmuHfE/YPMjIltKh8nlQ1jg94INKcHuBrUkgsktOEiD9Y7lByA=,iv:Ug2AJoTUQJTkkf7yDNi1w+8fNwDmiCqasrH1iQFcoGo=,tag:gRXGM3RNR5Uj5ed0jFD0fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
