apiVersion: v1
data:
    password: ENC[AES256_GCM,data:7ZLeuIXlUCvkBqh6ND9A0DPOiJnuBCfjSAQzgbneMAhD5ETQuJVMWOG6BJA=,iv:NWpp1/eUc09ju35SZJVvu0QaRuTk064vtIWDUuE4suk=,tag:RSq+0BhH2HOd62m7jCnSzg==,type:str]
    username: ENC[AES256_GCM,data:KFJio2ithZk=,iv:SMTM3C9Y6U7xII6q2ck5JOr/1pA3dBT9P44omJs00/E=,tag:N3PlMTcOoXWZ0G+Ax1O4ew==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: harbor-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cURuMHhyWVh4OHZhM0wr
            Zmx4UGIvMWtmMjZVbFJoTm1XMlB2eW4wM2hvCm1xaUtIY0NJZ0gvTVVWRmkrd0Ft
            Z2FkaWFXNzRwS05rWk9ob3d2US9tM0EKLS0tIHpLOHdlOTlYVHp5eTlnVXlhK3FU
            UU1qQVhDdm5mZVhONTlXa1U5bzgzdncKoSi10w6vHKI3SWokbZWCnSOpmwuTZee0
            Gz+MyNtrzxEMDuhA3UvjuURhRdNCujmxKclEFkQhW0EBpg1KWIVWpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:HMjwNBFco5FL/bC9eNn1B7LsEFP4CWHMJpTEBQbPNLLkgcLU32r3Kc9+kmo4Wv/HABFKwJ5PKNcglsKE9QLVKSMZA+tlaM1/9VPgoN0MEXx2b22e8gXqG4JtQzbQP1NqINrWGjNqfmaSnwpnIqrAKWBdJz9sZpiW82wVsr7XTVw=,iv:M/z+w5GSJABhmL2Jt2npD6hLbDnML7XoemDp9+5q4sY=,tag:LhIAYtftw5xwgloT+8ClMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
