apiVersion: v1
data:
    token: ENC[AES256_GCM,data:MboV5NH8kfdRyCK5wpYdEw9fnRwG0/7v0oEYOC5qC7yqPE3/LuZPitAK/r0kxXDtyxiPWq53whrz2xzLzFc8Z6tB2LhZR4DqWfjjp+MoWO4wGPXh0zps8+fSF7dtQZ3+5qswulUDCZPR2fZ2waeyKM5Lqdj6se3wzt49NXi3PHJjvHVPxW5+l+rx5B8ryj/YeC2OpAYFRdbc4QXMDznJEBqKKqZbC4mVVVa+DQ==,iv:vfUKxD/ER1M4RnUHbX67sE8kByA8hiPu/+bgUYHV/8Q=,tag:HPbSvNg7fqDhenjkz08svg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: home-assistant-token
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc3Jla29HeE9RR3JGMXhU
            YU1PS3VaNkp3anhCQlY5YXBHaFRnYjNsV2lrClRYdThjYXlRTlI3cE9DSEJkd0dH
            Skhja2lTemRqbFpKZ3JIcEVDek5yckUKLS0tIGhZMFFobGNvazZRNks4S1dFV1Fj
            RGwxLzRwdUhLd1I1a1ozd0RvQ1gyZ3cKqrh476iy/YRWb2y4ZMd7lUwZEYH1oepW
            oF9j6QkREGOP9cxeW9+CaUE/sLc4092n9fmPdiL8QK69kkpDK7vmHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:4y7BgxmEcyWpKEfpfV1rOuk8lgzXG3dt0KBTdiIQYdKK2FX9LpAK4p0VSLrdNS/XoXRZOMcbtcqr+uQLMEmp5LXbLbl0016hSvuNt89/Y1sLaIFjMKqbOGpHXW0PDMpBuxZT9NmmONBjeZDq06cFNCD0wiZep82R9eIt/9E0ad0=,iv:z3zKSA8Jptlj2gkbutUXcgvBeDN8uvSqs8otn2GD0PQ=,tag:GWAKMedL3+HezzS4T2nMfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
