apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:ZcoCM6SPvx1Ze8ar5Oj5/3e5zmj50W35zwLFh4TYvS1DqfEjJmxDe6F16p5vERB3MK+Bc5hkVdIMJ7HnSTtLXMtttBHinziEOBQNB5dfmnM+DyrTg3YMZXhHUuXiP6fDeSplGSxuM4RcdTp7AyM4LzqFAgfqWvCbk7Y9VzUovFJemY23srcNLz0dgJ+fpoj55GYwpvwwZv8RHwHOAA+9heXy+q0Besiv6/jJJA==,iv:pea0ZCfWphanHUEGPvhFasnk+R9fYRT3hxqvtuSQx3I=,tag:B1VyGkGe5vvqRl776yWRnw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hoppscotch-jwt-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMDRiZFc1ODNSQ1IvSXVa
            dVlFNk1IbGZuRW1VMXRKeU54TGFtMEFBV0V3Cmw2bkJQa3ozYWpJdnRzWkRqUHor
            eklFd1BWVlV2RURmVkc5cG5qbjBzazQKLS0tIHhwOGlXUVZZWnpzTUdvYzljOVU5
            dTFpNzFRTUxOcTJPN09vR0JIbmZoclUKaIoi11prx04DFq+Ndu4/5SPODVy8pTaQ
            hyGnHHvkgg4Bq8Rjqjn3FOgSy/6qaelQd0UNnXVHfqWMSPbY/n13nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:tRd1LjBzKlYrfrfB8FPAq1xIsHW81IIy9ZA3aCUPv3NSELLTIAv0b/G3F84JZFB2r5/Jw2md2wSKRkf/f9FvAgBu3zkavlIMr0swnYD+VVFQrNeYSY5Ui5Yo6hrXQNqgEdjG2z0iQpyj5xyUiIdxh4nMPXV7uf5T3SP5XGIgaMM=,iv:Xk6Uc5RE+oCNNIUTVELRA8BFLmGlQw4DZvQ1/7M+THE=,tag:ZjgwcvnFRLBEY8c2/PnFEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
