apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TlHhrtf1Y+Ll2mJwWgsF4H+9qWpj0W8qHINyhswoAK/AP/b3/78vx9dOhr8=,iv:iTD/vFzv9dYmC6pDAGGui4DmAtdhYzJecD8Ujhrgr2U=,tag:GAcvmgyNcdsMwcluKrZ12A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hoppscotch-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ0lEdGIvMThCV2JkdXNi
            WUZxaEkrS3d0Nmd1WlVNUlJWczB5WWJUSlQ4Cnp3a2pkcWlmMXBzNVNnY09DRVNa
            ZFNoeEdQWENPSFBhYWVidS9lMEFtUkUKLS0tIDRZL2tPODJvU2tjdmJRaml0Z09r
            MUhXa1I0OGVkMFJYdUNqM0t2K2NnK3cKTbvai6VBVpnvDvl9CAT7/IE5dXuV0gR/
            3RS9CH7UT0XWciAV9dxk0Cl09byqZ3JWcJcQNAZFT+iiRkfWgr+uvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:sC8xRMdN/lWmYPbYf/GdleHsIY8uqvQEGC3kvVwmemc/XOE2pGaa+CnzIGFuPSp99GEvlZPl8Yn7XMatFQdy7LO+OEHxwcBwIFy1Q/shElbPGNAID6WxLFEpudBAi5N9uzj8av8TqVMtVWFq/qC/25FN82BGQon9+jrzSWrPJrQ=,iv:YrPoRJ02crOmpTbbQhlNNTbMl1R0KmszjmtrSx8q3sE=,tag:ahxgPbfjPpjjWGEWkyqguw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
