apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:qe1O74DTPzDj9l5B/3HGjrdP0WUvCBs/ll1aTzA+vSXjbc2euagry8QV2PJcZTp7T1xltulyIypmoggCNoFimG7uZ/+H2PkiPUP5Supa5qsO3VMuoF33GQX5JEZ/iz7op9Def9HX1DXs2UjJpxrCtENqG5ZQ9d970DPedJYlmoR8VbTzMZpS6y7BRq9GMv9iyrCwdDBr8Vij7UCHgUKywmk+pooELS5hV+Ax8A==,iv:mNiSD7PN0lZqLKtNBzeadAQIrpCOZjD6oL3bO7u6Xv0=,tag:yOUXtgSDyZ5tYVe+sAgC3A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hoppscotch-session-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXZTREN1d1pxWTNkQ0Rz
            a0ttb1RoMlV6ajd2S0FHdzQ2ZFd0cTlzMDFBCno3QTJEaU9FbFBFUjFuand3SSsw
            WTRRSVBXWkp4bStwVWRCaFdMbUhtYVUKLS0tIFJ2Mmgva04zV1pnWklYcFZVaDBY
            QjJIREd2U1hkZHJUWSsrTmRyRDhlM1EKx4V+Sti/ib77rniJPmmUHAQMOL1UMk4L
            w7UplFWGNkdym2ts7UL9P8QWcT7IBrJIR+0iYQA5G7nEHNw7giIlwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:WJyyanMOre4zSxSdr1iN4BF/0POoyRoZvQJ4mpQ9okB8dEddRQe0yik5OF6ThNIwVJf74gqOqE3diHY3aGDZQ+2hPgInStodpslDlmTMk6Wt1nLvyVHAjq93WLAvS2/GLRfpp/mC4WMG5xgkkdGSMAOAaJ9LSWfgecWd1sVh6qk=,iv:yhfDasyBB3POIawsk02NUqj3SVPsd7BCqJrzFDTEsjA=,tag:2/c211+lgNxJPk2trlDwmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
