apiVersion: v1
data:
    password: ENC[AES256_GCM,data:nMgZNZYevn8orTSh0bx1yKmEPreLzTQZ2FW03xy9ejWl0fA99mRIUtkqbOg=,iv:gW6IiN7qxS+7ZL0ZCyoAb/Hlctca0CtT4XR0sKrl8R8=,tag:fwTETmrd1DFBEqsfh+r0MQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: immich-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UTBiaGxlb29sWXBYUVFo
            NDBpYzJXWWs1aDJBNE9vc0VzMnZJVmtKVUJJCjJBUGx0dWZHSkdvVmdDbTJuVzhN
            K1NuMkRuYWVMQldJSW1IZFVZQWYrZ2cKLS0tIDIranB3VlBubEVNUVFLM3hOYlBp
            amk4VlkwYUY5L2M4R2VZY1lnTVM4cjgKJi2QEYAUjjQ31aoVOzS98fTDxVtuAnoF
            Ly7zitVagMdiiJQysYPpBav0K4lLQLUVw6XZ0MsPLGoqpoM6uRbiBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:dzeiuC4U1eFMfi/t2DYZJKAzWocRPrxCC5/56O1UUMgBkkHgNuzoWwWTBxnebFjrWRloFeZgx8G526AN1hEeZ1EiLoj5QL81s13GLAzYViCwz5dsD6wKNPGJn4bbGsofKv/gCU7fr2UlqDALO0T28JYlewSaU3rnu1YvHQNG+aU=,iv:RCQQfk4/y5yls13j9YsPpDS/NTyXHvLYV+yQSp2pm4I=,tag:qI021oDIHQTug8aZtUbXcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
