apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HUQNoWtp2jpg7Nvi8nk4FO6/0o7lFn7/L5YFbbYOQJ3h5enRgUVgpdcZq0o=,iv:SrqnYIQnyKRJ/Q6+VOr1vJyVL9gARbChVSbJK299I1Q=,tag:XQu0rhXxsnX7K7aGnk8zGg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-admin-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SHBxZlhlc1BMUXk3WHpa
            S2s0eCs3TitFWm5vVnBmUlZ1U29aWjVuVVNvCkNicG51bmdpSURManFJMmNNbzZW
            ZTVpZWFFVk9TbmxwQTNQYU9aN29JYncKLS0tIGR0SDR4OE1jWnk1VmpuN0RXVmM4
            UHlZdlZUQVZQK3VnUFdhazk2YkE1cDQKLN+QK8U26n6S8hjef6Uz+mU5Iwpq/aCb
            U/BC4jkZT6VTBRcyYEi1gU3hm6+IMz6fnaZx5lDF7rbGcWq9J3XgrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:73ct5i3h5EGpIpo3IrNPQcLKDma3s5m9vpYjKtPG0WuRr7/yOSxdDuLg3zsE/kQ5pGCl+4cKBZLqYPo9iWVmP7kwwN4O9nQIXSgo/4fAwo+tTyGLjE1Arjq2MhgIHRGq3jAlaCKITtdgDQrh4Ebo2LmFN8isN5WZsmxXTtGqf4c=,iv:/KqIjUTFc5CZpaW6sW2UKHiIoKOB0CkDGn2ydxyrjJU=,tag:xeLT68GvyKnDYETlRaDkAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
