apiVersion: v1
data:
    password: ENC[AES256_GCM,data:voasSbNNo2aYSMzKfbApeGI85Lc+raO5y2qI9azMhr5TdHRfkFqxg37PF08=,iv:9inlRIIUuvCfF7McV2ZfOVyOwUweQ+NU35EtSJHWkFI=,tag:sfxTYsJxkhhI/qPL2HYI6Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMWtNcEMvNVRmNzNZTlZM
            YVk2Yy9pWmowaE9vK1hTMlNuL0tCa0VjMzFvCkNuK1U5NHlnNG8wbzAvekN3aTJy
            VHFpNUZsQkJaWUp5ZjZzVHluUmxhdncKLS0tICsrT1pZSEh6YlJwK0NYU2poOVVS
            MklKVHFKRUJkTVFsMkVtK29acFdRZmcKUOL2Ezo4xh/lrxiYW8GU/V0T6Wd+8hGQ
            nz6Hg3lyGiYeDJdoIL2uiymlJBEUq8awhrt48x+73JQEKf5JL56sbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:jvDjqYb5HjqqU33n503e8gTF/LiW/FYrWiYbpkOMVdhRB1voKZR88OLYjFDZwTY2apRg155T34ORHNgA1MO44ru/ftPF4ZL9IFBA9I7jMDm0hiHeBNWwfqRFBmthIPerU6OZxoh5e9V+qspVknmEy6jZqPXKUIK5CNBXojf4Z54=,iv:t/I0ApKle9yb1NkMdT5ae+k1ZFZcZZ1dIOqQMeo7a58=,tag:cNaNBfS/IDdzlVl8MiweUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
