apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:UQtd8O44HnG4eMot3jeg6ABAgL9nzokjiMQgOrV3skGvM/W58v9nZNYuFR5qOfO/3K/3PWSZS5u0+/ih5MmMsSDIc2x6JT4aabsSv+FddLwlA8U6/2K2Kg==,iv:XjZPxvEPPaRMoxO48nnRmxqAOmMu7ogUzlNsJt6YdKI=,tag:r2Q2UcXL+ffa4zbvKyYpmw==,type:str]
kind: Secret
metadata:
    name: laya-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bWhiRVpJN0JER0oyZlN4
            M01Ydy8yQ2JFNnU4U1gvUmV4aC8rbXJ2V3o0Cmo5eTdQZysvV3pKTXk1b2V5OFo1
            dFA2SkIzTkV0RjZDaURMbnJsT01pRTQKLS0tIFptRVk2OTZaNEs3M2g4cHVjODJG
            bHVqUVh0eUNTWlRJckI3cmRMUTVuY2MKbeK9aoVTmVO/FW7CLfTF4HE/NczP5I3v
            EvWE+FV0Ud1o/JXQePc01dFVoCCFqjlPF4ibgI7b7ilMwVrlqbPO4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T00:31:57Z"
    mac: ENC[AES256_GCM,data:vDYvdjbMEoRBnyXGTijEzy7+S+O7dGXbHHVW4+GqQAgC/oGvZURp0I/8nJgUYFwHi5xtAYwPOaGpfV0OEjvJQMA+zINWTlSpNZE8lRb3dudTNRCv/NWlKfCza95GtlafHydEKVkuoLtTyex3bHMlkBD90hlvl3Pbo9GQlGXPEEQ=,iv:NTw6OukptW/2xMYyPVdaqvb5DcUr+5ckpSt0b7fuVg8=,tag:p21aYrbqvobWke0FsIwG6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
