apiVersion: v1
data:
    nextauth-secret: ENC[AES256_GCM,data:XmYbMbq4VtVOxX+H31iLi+G9xQUFX3+t7wS2VhsaZXYzLpEZ8mV6IW20R+/UWRph+CJlJtWrLzAPwJrjsZtkUho80vCxDcAz9Dc29SUEJiUKd8jkg1K4KQ==,iv:DH3mPg9h8eyqNXKsjtteuLtvApgw3sIG4oR49e4LC0o=,tag:mM1lLGAGkaKECz4XANZE2g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkwarden-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dDcxaUZoQktvRmlFdm1O
            MFdoRXZoNml4dmxOeE9nSU4zQi9KUFl6WG1NCmVVc0p1U2FaeWVqdGV6NHNMYjVW
            RHc5RzhjSHB2MHNBc0VmbzJLdmJUbTgKLS0tIHZHeExBVlhiRVBpV2lLK2wyNitM
            cm5zVHB1bDh3ZlVWL3FxK0dBZUZnRncKva14XapJPMBU4CjUTE/apiKrPnaYMTUK
            +2vCuxZrc7bC4jrgmjvojruAzTL2l14zC86Iky4zEGobrOjFNfRmYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:XgJeoqEYoAxadJjQjkTFQqOQgMXeoAOAl8Ihm9M3djhrboHkdtEqT6n3fDqJ1U4IHnuZxZ7HKhF+qWBnQDUY4UX0kY7YRL+yoYEUZgQXc3e9DF3/npHFiXVyJjA8bzDSSzk+9RryUr/HN31y0Ku4ocsWGnTGOOZMgE8WcFkKd7M=,iv:YKRp47GiAAlCW5E7O+FKTsnCmugK0g+xLhcLxsHIkMg=,tag:H1yQU2BUCS7IFIttfkIduA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
