apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ey/MH3xhPqZvSOyXNDIPh0LOwVuKaL9E5CUTUhcGEZCKfhsWWC4DxZ0l7NE=,iv:h/8C6IkxRb0z5GDwC/UyQTnLZYAjKeSjm61fENCGd3c=,tag:50/GCLOoisLrNmi2/p1KpQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkwarden-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYzBiNTNzRWlwSlpSMUQ3
            VUFXVzE0NHBNb3JUQ2FnQTZ3NGxOajg5SmdnCk95SVVlN0o1MVVTd0RGNWs3VXdG
            NzZjWkRDS1VON2lhZy9wU3A0YXpyR28KLS0tIEZmdExIWVg3VWZuMWRiRGQ5amln
            dFJMdU5CbWlETm1PVnlGS2RpdWFvamcKDM0ho373hhP7k/xd6TBFVIGicLwdsV2A
            IXfWl0nG7Vm0OzMc/1mqH1tWvz/uKpoS+AV7bYxrvQzj5FuL8s0Xhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:X1xggdGoBl2Hb1lfzsBv3Wbq95o/lX4H403YIsneNR2isEmCrjqijDZIbRS3ytpuS+Nh8e/cm/IDcLnkuvC7XcdO8o/s5kXZokhFL+YC93D/LkUYS+JZkdC/gYhYwbotucaVdDYxsJpb9fgAUuA9lht179/aBenYosxpDgOEqVo=,iv:QBGbYLOvMT8pJGgQk9YXyxU2xWTdxMC5pOljoAwZE4Q=,tag:vukHhQZ1e7LTUJBIY8KXMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
