apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:L3oyGxtG2v4lL7cU7pTAo2QvzMo8J3wrsrRTIkCfOfNMOs2XQ+zrx5gWbyVqeQj+L0Y7LJ18P5uC4SGO96c6Cl2uOSSakRXIkKyjHAEV4FXO9e+o16ixpQ==,iv:LuNSYnnGoJ55wVNPR9GUphEsD3XH6nsliFlkVdHUKPk=,tag:7ErOTyeedfdhnUq805+rhg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: localai-api-key
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ0JPNFhPaDNSZXVnWlRs
            dUZ1clNXNjVkWXlqeVVaeDJZOFlqSm52Q1VnCi9oWFNvYTV3VW9KS1hmRjIyOUUz
            K1ZFUVlpU0lFSmMrRUxWaVh0MlQwTlEKLS0tIElhQ1hTRmpVcloxRUhlenM5dnlo
            VXAvTm8yN0VzaVl1VWI4OXhDY0FWUUUK8T/ooCzu7uAOGtjZ/rneSoVxUEqg3JAt
            bW+f3q8/j32KTS99CncY5+/GJe0nK0WMmCSYMmSQvWIqOPgNIF49Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:Swsxz/r+NKXM+Cja0Qe650goGp6Jkqo1F5qDwjv7sZWXzkBhBI9gbiZVfj+pcOz/kLmlbmpmPZwqPU2TpTvGBQCfqowahJkbdCxHa917ldCGHSonfj0VTjsNOcbW86UI8J3WVMoqPJxjQ2PF+EK1DGs0R8OslRdyrzVJSu37EzI=,iv:sY+6e6HUK6bFNc5oMSpZVILnDuXUFyOrEpQWg2ZYOgQ=,tag:KAJQ6qc41bwMIy28onBR3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
