apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4txakly/hBfrDLH6GIBpbCGKETGMJ0Nmsz19uGVYBSUlYugLtD6i2tFNxQo=,iv:VOx+lp1OI7M7wSdUqv5erlNjTgSHBnAVMzIGWY/iUco=,tag:icopb5m5cFGgG1F2mt8zZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mattermost-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbmR1Rm9LSldEMU1BOTZ2
            UnFRN3E0eGpJV1NSZUxhVjRQTlVLcHJwU1Z3CkVCMHoyMUlhUmhObURQVHB6VHJT
            ZVRwV21Yai9FT2R4QzNncVNtZS9OSFEKLS0tIHo2V2pzWjl1d2sxMmQ1VktpZEtw
            ODJwR05kbEpHbmJTSWpVQU56VHNCZnMKEwkyQyeWsASieor07DIxHoHMy9i5tf/t
            11WQbm7pZ3DWT0qqDX5HtAJG6WtfTQDceYw2FUluqR7z17+80Efjhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:dJoqUGpWs/dg0paWHP40McuN8eG0S1bmsKCYPVHndcwVambQvWMhZ6sjTFYOH5yhuJna4VAnUh84xwzx0A/jGb44RJdtNm8mDXx1hoQOkfqVkoL4WbD4Ay1cMRdHsMi8YhQFebCp1xtGKAyltg9zR3umY0BJhTc1QTdqv/O9Ruo=,iv:DGG27FJFtOleYUHM0ZmLh/EWtmiIeWFkigWnrBdqUbY=,tag:0m/lAm25etCApIdBo4PrZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
