apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oADmbRDcl9Hi7xaGSupmuqiO4gPApdEBqd+zfG83gIPOAfp63pjq52ITLq8=,iv:j1uoiZSbA/jlc0j7pnewYv2yIEmbWqeAt6W6tlmvPuo=,tag:w4s08iaaUzVJMlwl8rh55A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: metabase-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRHpWR2RZZkJQK3pSb2hS
            b0dBRmpTQzFydHVGZ3VYMERFV3JkT2MwQ1JBCmI5SkU3eGc5Zy91TCtVMDZlK3o1
            NG9KOG5MYXdvVmdHYnJiNTZqdUFpU00KLS0tIGI1Z3EvaUx2MTgyMGZZSGFqODBH
            QlpySjltRGF5ZFZNRGVIM21GWENPVUUKHYRX4Clpr4LPlCZf7jbA4Y4+ajEPxjtk
            N1cGLCIGI2gvbOf5VBNywSpPjxpGjjFywWG57rz8VTzd/RX5+Dr07Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:lzMomg2OadJleROPQLxfaMnTYaF9817tmwSGC5RONqBo8ljJ4Lc5GeXFAnOW04KnfmeaatGwZhK4j9OLbSAAL6L1NlaV4giNcBeLxck8KVvLxXtBziOnyLIS7Lqg5YsAcI+apTYZH1mp7bFzMktqvbQtE9KTxmlYX4BBGRag55k=,iv:QRInxVM29Uq/Xg6C4zDc6+4tFX9qJH2YJ5FZMfbY49k=,tag:B2SBGa7feGt5xqvb1bVD0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
