apiVersion: v1
data:
    key: ENC[AES256_GCM,data:36m4hxff4nck+zRTLYEBPb8Qwps85Qjgn4dpf8/nkx5fXi+Ru7iDjU2PJPI49PG0EDTqpb4+iOrw5qnJNvk8tFoXNWkjZ0U6dmmM1x8wBZuySYIjPTs35er0lHVjJ5K2LgEXim3n8+jjL55P//YyOACEN5pkcsU/tL01WfH6mFSaBBu4p+aAtjMEn/pu4T4emyCQO2kFhW+eYgON2FhMz2ffy8sxO5123Stb1A==,iv:1A0+p4l2dIgx1NuduvqCkqaCCpcLbpktbfoDMx+dHcs=,tag:bRWnkhXsZnxdZQ8ZNcINJg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: metabase-encryption-key
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGRmQTN0aDVVRFlqNWFR
            MW5wMzZSQTNIdW9ONDI1Q2dpQ3M3dVhZbTFBCnExQyt2dnJOK0JtdUpBYk9qamMr
            Rm13VnV5dmJMSW8xVHpDTU1xeVpzTTgKLS0tIGV2NzhEV2JvUEFtWm96elIyczdj
            UnJQWE0zeXNWdlJ5UXVrV1BKdld4OGcKsGwnV3/t/1myMUGZO95FH0xCmC2CIqkw
            r2AI+QavbVmkeyYcT84cW3sthIR9H9brFM3w+Q1Ycc7VtkpwvHcF4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:ux5jVG4XqhW2yWEXrXS2EOlZmMzoPD9U68nX1U5BdgYyBtE0+dGIPwkWUm39cK0rVY+AVn9spiPUrgXJp5g4+CtYQYtkbkcDgytUBqBXw+8UF+piExIjFCSxwI5rr7rVQnKhV8JIjzfnJ8qsKQC6awdO4T9b3Xag8Xovk4LXy2k=,iv:C1Rzia6EfMRk6CwKIuGoDn5KkvuDsZ/KtqkUpd8UrtA=,tag:GlxhVJmu+dZPZ+xQVjYCRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
