apiVersion: v1
data:
    root-password: ENC[AES256_GCM,data:KK7HO90InEM2PAfBZMueVciOeqLwopo+D/dK0nmMNNgpAXX94Vl4D7Heahc=,iv:Sfum+p8kB7e/2PwVVPmNxJI37taqWAfgX6BgXblZ+5U=,tag:co7ukx1S+0Q5sIm2OZD9/Q==,type:str]
    root-user: ENC[AES256_GCM,data:RB7cGuwHfJ7Z4qtnVew86g==,iv:WUuvm8OTPykB9Rhhj+zLsskp07NavhOLbyelXn10IKM=,tag:SJKZlc4rgwMeGL5Fi/AVBw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNkkyRHl5cWN1ZW9UTncr
            cG91L2kxK0puRzAvWjVIMVVRNE5nVUVEYUhnCmIvdWgvV2Q2dVFJOGtGR0pRMHVl
            S1EvendFZ1BncUxuRHZWN3VsSExDc3cKLS0tIFZUcnF1N0dYOW4vWThjSDVlUG5v
            OTA4RGJjOG1KbEJ3WnVrdGN4OFcvbkEKo7NjG4EqsGTBVVAlpPRw70Hogo457FXX
            8bSe6K6vdBwKEvIutkAq9xNIX6JtmO/WM+yW1CocK7rwZGcCNNEg6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:2csl2zeC4EbZo2mPJkQisqv1xElKvuAGMH6fKEHDGTflUnyIGCl7Zpw+A2RLmF3xvfVb/js3G37vE6MaabCvVBP0J0hceJLPBuOzkjwg9ciSaDfWS7HfAP/7koUBQXdVPQOX/bCXqh3UZwF35QKQgMLpTnqiln0GAt2EzwBR4yk=,iv:K/yPh/IpArlibMaQIH2L3M/gQaa50v93Ta4G7xF6aKM=,tag:5DlY2apDZO6iNSdeJ3DNJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
