apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:EBShVWtWV/kDt9+EyyqPR58BRyWbUJOFqOLeOw==,iv:bgXOM+tjkwB6dEnkVklmljl4qlDb9oF7C2bs1BlHPNE=,tag:DZ0Vah0JRgEHekYgeUQPDQ==,type:str]
    secret-key: ENC[AES256_GCM,data:uIWTMb4rHc922QcTNIot47+w0dcz5aHJG49TrGIoOyfaYb2psX9A1P6ktn5YWt8mdqbJLpQyx3ReEX7/1wVT4hN+ZT57eRiKr83yYWkxVKBdQSxuntuq3g==,iv:1jzNn1a6udEdmID5ZIO+CSy3eqFmPSicT3amzegP2ig=,tag:xGkmNkxYmzDpOkkP6Vyz7g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-credentials
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXAxMGpvMzc2eE1GUVhS
            TmRHbCtBT2ZvdW4vMFl0QkZyaGhKdG85SkhFCjJ0bUVpdGZxNTJMcVJya3hOazJj
            Y3JsOWwrd0dOUCt0eWM2dEFxVEQ1ajAKLS0tIHdEZUhsZnk5cDJUWWkzQWt5M01r
            aXBzT0tEVFh5WnQwdElyaFZCYnd6RDAKCxScokXBCVuCjOf+nGOgwPE8s76fV1DH
            N+OWEC6HhTut5CLtzyEBPdYQWwcn8opsNJlXmkXuvOWZWubaFOFA0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:Rkoy5bRzXuYNpFtU/E97uXTBdnOAKCJJBSL9W66aULGgeBxIEE0ivu2eccdf2FuorP5IamBa2D63GpXfKRt0HbWJRb2d7dOa0lH/IR8HsmR9Gw/IcY73dtvjfe7khsBf90G4yAG8Odz5iAg1upRBIwcgubt9S4pVojoNGM8cSQk=,iv:mQRWItCQuvprCXU1T+blZi7BsM3YN4XbrvA6S8ilTiE=,tag:+C5faPeCJ05HZMfCFnsOug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
