apiVersion: v1
data:
    password: ENC[AES256_GCM,data:nJCwm3P494EeIJYzjYGDL+KWjITHBfprGpQphWdhH/Ikl4iwGTjNC4zkZU0=,iv:wlT2sceoCnIuv3OUkZ74TnqoTjRPmOdAmHjti/Bz4rA=,tag:56CWJykbh9HTEhpsZob+pg==,type:str]
kind: Secret
metadata:
    name: miniflux-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoODhsTnhxY2pKY25IS3cw
            Nmk2Mm8wQmlsMXlpMEFoTy9ZZTIxa2xjQVI0CkYzQngzV0lJNHdIODVmRStCeEtK
            cEpFNXdhTGhqTnVUbklyZk5SaDdrcHcKLS0tIE5RQUllMmZ0THJ6c2JWV1JFQk1R
            aTJUa0JVbW1KYm90U1RkNFU1c2F2MUEKxYHD+ti4KsT1hm7VIk4Mt2nXi+JVQFmn
            K0J7T6fruZS4iddU0WR7kipGT51mo3xZCzgpDdw8WkU7Qf/CqGKykQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T20:13:34Z"
    mac: ENC[AES256_GCM,data:TVRqVHUK4i78ch1Gi/FB2YHsEZfWHyBjxrRpn1SEj/gQDYm+clz3P2lQA7gvHvggXqBoLayefwccWQOfmRNxOCfg4zGm0PJ1eB8XPdV6c9tY4GA+TNpCTlbwTqNWzkMgwUz4t2UF7KxPElOIM/+yK0zAWp3bacs3x7NXOnqsfeE=,iv:Z2YnnspDULyMrJSjgduEeFhpumHfhr7sDBxGXXpJCpA=,tag:r/fZbU/+om5Fw4IpljSw4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
