apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oWmZt1A7GUx1ITzrcY+eVQZQwf/lQGnDjXkxuELgSH1R18MKf7cLBkE+UH8=,iv:LMOVUNUr6IgLBEE6ROxAQ+5eTVF0hXxRnFcj0EmRHmo=,tag:zA3jClV6EnTptdpj4xetJw==,type:str]
    username: ENC[AES256_GCM,data:5vWHeZ/sxkg=,iv:4qRCfUmbhWUveJrGe6ZtktfO/zWMuEK+r0qxd51baAY=,tag:H1RbVgZUFjKU7iCIVre/mw==,type:str]
kind: Secret
metadata:
    name: miniflux-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU1U5Mk9uNVEwS2lkamVs
            NVd0U2Y1czFobjQzc0VoT2E2UHI1Qjd5Qm1ZCjhqREZpVHhZbFE3UGh4eUZ0ZTFB
            NEZrT3dIZDlxKzhTMmhzU0hmaE1lS0UKLS0tIGdRTmVWeFk5bExEeUJrVUMvS3BS
            MTkyZFNFYmtnQkRYZFdQTm9UZVdlUkkK6CAeDfszCtW54JjMFTLv4h2lplD8Fbr8
            3fk+a0fDEPbE0lLXprjqCyBTeiLGTjIuHn0suKgGx/e4jTJvcPbSzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T20:13:34Z"
    mac: ENC[AES256_GCM,data:cFTOFa7y3524Z+bxgwdrnplI6Bqr9M8UOuDK7KF43DdVJyt98Scgy3wICLUO5Y2jJ/HHjk2Fwn0XjhgWJc+mLdjCT0p3tAgMnn8g9rOthG1mimXLNBGfXJU7RwIjLKfWBltfF4xdliKTp4r2mA7XT//xfqRB1lw9789IaY79XYY=,iv:c7VMq71Z0bDsciW69b888mxRTbAs/g9DGCVUTPvg06A=,tag:iwulfQi2ziPT8uzbbrYLLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
