apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3h/ufJEDvJ3pX74O5OzwgD2lLRwv0/3rLJkma5gZbljE/XO85HTRw8Wv3n0=,iv:m430/B0ubLs4PBBNA9D9qROGJ5XMfrER9y0f7+yW5DI=,tag:QOmMsBF8blNr8OVRiQr65w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mosquitto-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBranZTUEN2MDBJbUdMbGs5
            VFJCTDF1dTBtdm1KNnh4OTlZYXhQUjJRNkFBClZoWmVGdVY5TWEwMHBCZ29qbll0
            T01CSlc3dVc2T3RiRnErbFB2cmhwZVkKLS0tIFo0MDlDQ0dCS0xYZTJpMjJRd2F4
            RlN3QXU4bGdkaVBDVWl0aTRvenQzVjgKqyH9kGq771+A5ow8NfcMdatLGpXITH1p
            IpT/0rutptgyWv75ixu4HD3WaQNbCcbIjXjtZ3i1WrkTwNBkjZegLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:CzZfsEcBnTMvq6WZJtbjo5S12d3tXWiNMfqNWUAnVjTAiZ7hMlGLvTiememUPfP47LyGPButRk9rSKsTICDSyx5vWsVaPYwo6EpLDaF7Ey+ey7irzyEBeNTjIB6jpQLTLwRkJDXlJ76pCixkekWt+/ODuNUSJPBrWdDSnm7nYxM=,iv:4N4s1EDCwsfoCcyVk1vT5diILbobk09GkQpkxkDUmfo=,tag:yv8RLT+oAB/1gBfp0aCYsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
