apiVersion: v1
data:
    password: ENC[AES256_GCM,data:flHL6TGEtwD7a9OJUJUOH+IjI5bVkDuEFhU0MNGnsgfDOcS33Pn/GADBTYs=,iv:7lkqrVvRy88KNe4qpjBwiPYj7oURvRvhy9xUMiuFQMk=,tag:Qt5PbchJO3Ns9KCJj+vs0g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mysql-root-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS0c5MHVOcksvNmdseHh2
            L0N4YU9ibkhVRUM4NTBMWWtDS29GK1NNY2pJCkxpNFRpTzZ4c3JqVngxUzNiWDFB
            MWVtcG1iNmdLS0xqT2RBNHdsQ2VrdFUKLS0tIGdxNnJwQWVmNVJUSml5STcrWU9P
            MmNoWHBaVklQUGdkWFpGUEVXS3h3S1kK+EyA5sZzwiIMLf11ohrn1bxBxNzBRMN6
            XXCArd0om07ixzeMpi+hbPOq+isJCrePD4FcVR3bhizdaT+6va1p6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:HSk7CdwoIPWh8LE6d9EaZtaRBKGUu+JezcFLc2avoPbroFzBqXrWYnvqqQRdhWM3mq5jYgkLKtiK9JwC2sTANjBKtLelYqdnM+1+oiTUTO18IxcBcLXXdAoVf3E/lC65EDO6H/FiN83nezyopdK41D+Nqb9roxNwNEVIn7YcTcA=,iv:Su4tLAFDKvktYMbuw/DCeu8DhmNFDnTQn8CNXfQ/3h8=,tag:Aixt4RueOK8DJAlHsAsWeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
