apiVersion: v1
data:
    password: ENC[AES256_GCM,data:NP/dxY4lyDH33c1FLZWDM9eFCGL5dZV7Tjg5zg5U854LNQz/SezXXV9p41g=,iv:YaWBf7RsFbk+LnhMFhFBaeW0DRB5qnJu8PxErPWUhuk=,tag:h0c1t9lgASHSPcEyyup2FQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: n8n-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYkZRZnpPSzNDYjBTWHli
            NHUwbjE5dHh3WjZuVmFzanF6SXNPdWVqWFU4CmZ0YzYrdTNRMHVuTUNJUmVyTTZW
            WUEyRjdaR3RuSjd4dnRhbEp3MFFUZ2sKLS0tIFpLYUpRakZDcXBNYlExZXB4NHFO
            OFFvWUxIZGNwVmNvRkJ4bmFybzNxMk0KN8aq5Yqzti+ppUMWPnNLxdDoxiHYYE5D
            naR7dqUEVyJfVPcmb9qv121ZC2/QsB7dPmZ41dDkxR4AN3w8zDfSGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:5VIRYWYgfLw/NQ/cRCI4YstTlTYrqUAO5cE0U+vYCsTdkDR04XE3Bwl55iattaxDzyqyiGUsrRVEYNMVL0Vqllw80JOmz+cuYfXSXkxvgaPDBrsbaLyhm3dOdaBdXU8wGaXn6EQE8xosZHQ8EeVXIGrB2Xb8e4hqqxACXshNWPU=,iv:r7v/IqmgWMOtWUyVGj0H8G2eK3lxZUWuoTZnhlVax38=,tag:YA6cvGCrd6EDKg8Vpji9VQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
