apiVersion: v1
data:
    encryption-key: ENC[AES256_GCM,data:WZ///iYRGJPsvBPiekRERSlADvMz4Fksm5HNA+IsfCQMtHbKw6k+NQRR04hpfkiyvdzv4+xFJYpOzX/QqBbQO/Ug0InIKkeBBsCbAg6np6mtIBvLObN4ZA==,iv:QuKLP5ho9XOpsbrOp+mQ5qaKoUuTZ86qDdoJKbToOto=,tag:a9jrVIHEMMc9KgndyCdsmg==,type:str]
    jwt-secret: ENC[AES256_GCM,data:Z/TkSLVtBqxdB+shMlbl8UMzxJJt9fJ/DhednyvzHwR6tfTa6H3QTC0dDgERSORoGB4jV/yj/U6Y4tFOFQvMeiWDClYq+gIGfnBuE4asBYP/SESWycvEhg==,iv:Uyaew+u25KHlq7YlpgQZhalcAeSyNLHY0GDl1HfdcH0=,tag:6rM/QX+Gm5oy01m4VgADaA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: n8n-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVdNVklCVFkzY2s3eENs
            Z3ZISEhORW5uUzJvTyt4RkcycEZFS3d5V0VRClVxaGZKNjE2aDZuWFllQUVSa0Nt
            Q3JKdnk4b2pGSkhPdmx0aUVPU2hEV0EKLS0tIE1wZzdTZUhLaU9iTmdNaTRjZDFi
            MGdiZTdqWVhBcjJ4MXFzTXE4RGRuMVEK8RTrHznIZfDHpkEDCln3hoQO4S1mw3c4
            YhzmT4l9v9uZmFobUrgcKwqi6rNnQscUODO81qo/5qABdBfUgCciAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:OgvlnmCfiKpyITpCrqYCI51NcXY/7vJP26XLrTu/HjnXCwPJ/NT7k79r7k5YC/AgedSlswG8320lkTY1PGqlZ++U/q/1+wf/s93VJLs9TCRawwAuIr64X+2crLwwtVTm7NiDUlJ1y4zwGV3h89sb/uYq6JiN1JQbxXlgoJxP4Fw=,iv:fv9iPcpOzUzwI6yanbnxGJOzxrXqvXxW7rJsT7wntbQ=,tag:iyx5Cf8Lqkq8FFZRHtU/Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
