apiVersion: v1
data:
    token: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: netdata-claim-token
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R3hBNlBCM2dtNkFNaUcy
            dW5CblowbVF0UldicGNsRk1ld3JjbDNURDFnCk94TkVCUmZsOXM1QmF3c1lEY2lE
            RXVvOWV4UVNiVk9wRUZTYmNrUkNURm8KLS0tIGd4WExoVEFJaXRpSU45a0d1M1NC
            a3Y4LzhvWmNTWC9VdUtkd0Y5RlhpNFEKu5oAJxrWkYZdelCYQuDRvkP6LYFsCmpo
            Qmh3v5KYqqzulkU+2KHKhOi12OGdwRjD9NTH5ZWrt7rtMcBiHysjsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:EmVvjbBQHomGy3IWKPaaf82/fab6nSq3dH9uf/r/TIhpXkStMX1dvQtnEQQm6HF4WjLafjyZkat+e+A7D+H4DjQHBkkTeK1R/RYGXvlkHenHG9EqkDKf4AyU4FNeibu5uGn5xIkjHCuVpljhV6JFPMRIzZr8Q0xNtNvdrv9mYSY=,iv:2FHO0ggtfm2efJzOiwtNdvewKsuRhbIqOoChcwXYiMY=,tag:k+MZiCSZFSpjDQbNXrNndw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
