apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zD/TozeaSKy4CfTRLw2U4dXJaM39WluPptshj2TRCGeAOXX9NVcpjcYYyHw=,iv:DLjn/BeKfcR4VS+WiWrkZeb+k/m9cqi/N2Kgo8k/sIw=,tag:LfaUEjs6PiTjhaWDTob1iA==,type:str]
    username: ENC[AES256_GCM,data:YbSbOhZ4s8M=,iv:B05ngti5kEOdSK3OYlbNER+O23Y3Q2Flm/9QghV+U5w=,tag:i65F2luqjX5J4cB3lWC+FQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb3RCc0VVZSs4dDBIdjgw
            SmlQaE9ETUJBNlNXTmNUR0pjc2VLa2pLWmpvCldNamVNZnFBMlVMcVpEWXMvb0hI
            Y2dScnZQM3l6NVFOVlBUalBZSnlJL2sKLS0tIGxnb3l2c3lEVHRFQmhEeW53YnE1
            Q0xjR2xQdWEvMHlDMmZRZlQxWk9BZXMKIWPFlhhk062Ov8xY7NqM3/j7UcMLbrMN
            GQG37gQq79CJWV8p08WtSVQrmKPZEgjaTAsGrQTMrjD6Zh/gM5tX4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:btf/LnOMbwSsIFevJfQH7bDqkD2/PMUP+I0BakKXz1yT20yzFSZrtB62haeG17eWOXmsgEBpLfdMCxw1MXStD74hf5RiW1bv8ef5f7o8YYRT1xnjwEq1uF4UV3iSqznfeYpUgE3XT7p82Iqsmrwhl79U1kIdsFAJG7sXWlUMYmk=,iv:rgeGCb3FUMIBorZfhv4isZUHdTOTxREe1/JEEc6OTog=,tag:obbhKs/A/M3KBzihKHjhZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
