apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3YovW9DPYfZlT2TzTxKOiHRAYfNAfbN2Hwgb/yXVHw1uJ8eIXO/pYHGeajo=,iv:pBe7jFbd/28HMnxGs/DpxOQdH9of6TiP8BljNPwr3fQ=,tag:mPk6f5uM/5ZAL1p7GOAj+A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MDFkcVJMT3V2bzJCSVdt
            bXhxWkhPZjB4M21hbWU0dklucFdWMFVieFFrClBhTHA5RWhKZFhsTFg0bENIVjJM
            T1RQRzBNN213dG1IOXJROGk0VzYxZU0KLS0tIElrWFZLaVdNL0MzV204UTVyVUU5
            bVltL0RFYlN4RktYbWJDaW1TMTlGWW8Ktl1uFrDBN57EBDD+sCPgjxQN0JB13yoQ
            j3XtsVirf162rGqgpZoRbstUjYSQujYyPcqKQmd9w2NVdzHd1WU+Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:YRzVY8czIV9+M5BDiCF9+qfcEm+yJgKkwROFL+oVHJbA91EPSJ3QTdalCYG+mw1Df4D0N9BHNoKlSh08Ddz4fVDm61AaEYYl9PTXyI48BG6fwV3JtWbajXT5eLqc8bu/Q0Yz423T6ypXn/Enfc3r49SVppZ5F3Io5qY0IYtbx8g=,iv:oodNLjjKcFBius2VtmTJ0wWC5cmRUO+d2cSl/OUpazc=,tag:D8A628Dse7u2jJNuPATvPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
