apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:3ZAhaTLbkJss5f4kJHm4Bpzdh3hXCVX6QPPYBqiAIKxP1nPbVhTgjf+Z4fneggDmZTl64uzaAcJ68GBoYfFfyACGl7k4qSo5z6sscaCCJ3sQz/rZIDYXe7BLkpoB3ZGbPuxD+24vGZph2vAwgIPKxkgP1f5oouyBAQVuLtVpnOMUmZPdjv88f+qesQAa3NSI+9uKd5H+GAYcBcC1T4D59jzbJolBa0KhtSmDvA==,iv:kDFilPa6DjSjhP6DQq02pH5nbN4pRwutzFOJW1oXq1E=,tag:MJPbe9SACFsNpXqoMEqakQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nocodb-jwt-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UjVBOUJUd3dTb0liWWZY
            MWtsWXVLTUxHTzdVdk0reEZPRDlmOTczeEhJCjNBTS9MTkpraUQwZnZQVlJuc2Fu
            RFlYNHBNb0I4V3c2bkNtZ3M5VUJDQTQKLS0tIHJMTzkzZEkyUlFudk0yT1VaY0Y4
            M014aUZTc2pPLytCeC9RN3NVZ29uUkkKe7hWdoPs1mRCeH5DRdeia9gq1atGjawM
            wCdzI68W8cxsY7UFEWVJNSHlcwPzDuSVU32WCtE21kVQ8kGYEQaxXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:X53yu7rU9fhtx0+zDtpqYggye96jon0XG42xD+23Pk45oDgfnVNh3A2ZpuFFlpZUcxHZpFPUxgt1aFXRdalRrSAe03VF+mP7WO8l6i5bK/j2sHw/ewlnhcwLL3Tg3pGyYKyADJmGXCHj0Yh1JaxDKdH1o1cmg2PiQnwJAoDGvlw=,iv:CQEMS6jZQPxpo5h1qbmvTZX9Wfb1HDSGd8SNF/2gUrQ=,tag:G3ewWOdyXtPAx0mTzduMZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
