apiVersion: v1
data:
    password: ENC[AES256_GCM,data:7nescN2EH+K260AJadskrs/SD0slWSmlhWtJi0P2qdeyu5yr3IE96NbEuJA=,iv:mpIM+w5MM23tTZ9sTl3hEg7srsoKPykdVe1Bk2ys07o=,tag:wPBimvCp06/V5kpSaet5Gw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nocodb-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWWQ5NW9GVkg3aHIxdDRG
            bDdjMzBCUjBLQ0VUdWpkYURzai9Ed1M4aGkwCm9NdXZKb0JmY2dma2ZKd3BGZVZa
            a0dVd2RsMUI3Q0VwSnhWdU90S2czVXMKLS0tIGUxa3hmc280RXdaNVNVVDdPc25k
            SjRBZ05TakgwQ2UvV2lFUCtycXBQekkKxtvHHylrgLuGM6gjXxB1Lvgppv7WeoHt
            PiRzJeeLWOjC7q0LLmgLNufGramwpnS4OgpYnmeACMun8xPmLWkQ9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:naX4ox0wYR2TTTCWflHsZQpcgUlZG21LzHx+OfRpVbzzyItkNFial8gCsSxxyZ0340SIc6PcW6z6QJKLJAf51FgIBiYRHuWK/tFq4xgltDBiaPspCghhU/pWIDlExKMXuDsSklDOvxPHXXogfb1dO/Lax838PwLf9wE4ZVA0PCI=,iv:7GZyvFtTKtsuQ3P71teJVK0DTFEQu+9Pa6LwZ/SMa/A=,tag:IdrucZJ1JGf2ID/Rxm7nYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
