apiVersion: v1
data:
    password: ENC[AES256_GCM,data:N2fQhaKkd84W1jjXmwo27ntZ939LEkdfZEeSjTY8agdS/CErUAQMsYHVBU8=,iv:zVT3VvAGg3U51baTP17hASHQZ6+RvSa7Dy+6dYQKWNQ=,tag:4OTBdb1y6CRkTbaKoyGzlw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: node-red-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MEx4YnBzYzc3akFMcVVO
            S2FvbVNUVHh5eGlQR0h2REVaYTZqcXFURDFNCnRlYWM4V3FROXVUQUlCV1Q0TVBK
            ekx0akN1NXpuZExtblBueWVzZGMwMDQKLS0tIElrZ0dPR1FPV3VHN05UMVg5QVQy
            Skh6cjJscVB4UHRybXJFQ0xGRCtrK2sKOVpCGZYlw7aCte+Ltpi69KnBdNet15gj
            gT2jxaH8X0dPGi44Gohj04+v81KBJXH+BVR/cSyohhxyvzdlcPn9vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:rj6wOM+ig5t4HEZ7QcjjTD6Z0CsMNAafieFTzU03Swr08R+0mbTFp/tA43RDHRM86w1GHHFo9PPCWSJ39+Ebqin5PemtBsmMc46tbzo52IMmCeJDsevxw/3p1juh1vYUQIqrZuhkNJDzzQfUJ8s1eYwVIBH1yZWOaqHa7jnUa+U=,iv:pIofGxCb1MQyBnyuqr786yY0jiKIMysq/n1KRssarOw=,tag:SIoWM+j2v2Bt0orsKI76XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
