apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:gc+8DTbn+IUC09L7V1g6pEwOU7ZPCT9qChZQBMVYxKSjrHIIQj1bv0J3AyN/NLsUGtZGnzxWbA7UfKHalIOLVMgphhdMzpPp+KN25c7SJyYC3vrib0Okhg==,iv:sX7JbEq+WsGwLQOI2OWKPbivFZzm94mtCaMGUZm87eg=,tag:AYT7D7ac8da0Gu9eHJH88Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: open-webui-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbEV0MDlqZzkvZEFtQk11
            d3VUdUhodVlkNTVZWndOVEQ5eXJHeG5nWWhnCk9IVlhra1o3dk9FdkZTMGFGUWQ3
            dHV6TjdmRmxFNUw2cDJCOUszUXJyb3MKLS0tIHB3OW9wZXpLVEhFY09iMWgrbU5K
            ZU40T09RUFVKRVNOOGRSVjZYUXBOQUUKEIRNTfB2broIZAPnE0+w1y2JfU35Rj9w
            /uZhGuJfZxl8cGVKoZ56rKKms48KrNG/e2xCyjTiaUwzL9xUSztDUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:oRG30OV0xmMqXB/sS9pztJQexJFVmQEWYYRhqGeUWFIATfbD8w+hZp8A6vm/J9GRRVo2lDhgchdleKkTVNQaoKphO/4DLferDrf8VWUoK/ZFd8qM8w4mdvyD75Dee4OtV4tEQAcpSOaLvNcGzhyvG/2/sCe+/KYNEWqdrETSgBo=,iv:PaKdwt89FeCwNeteM2Ta/0KOmFvHgfeCrisrB1BTqPo=,tag:deKA6H/stXVuMlU4eTU6wQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
