apiVersion: v1
data:
    key: ENC[AES256_GCM,data:Xaoizg5LhTqZZc6M0INMJQkkgFmBkHVxtdeeEutGoYExae/tbU8760GE6BEq9gM4g8ggZ7GKwXogupiDgmac/Z78LA77BnI2MNU2GF8etHKhjL6c65NIRp5Zohg23jmuMKxFkf/64cX8A670uacdrQLE6nk150+WBeaurzjzEZKytEGb/F9t74ILffyTPp+U5HtRLzYlY9Xs2KgU8T4hJoRsMSWApPRjFDLXFw==,iv:z349Dl0hpTDzBJPEIqe1F4BUzUA2hpu4CKTgv5Tw/S8=,tag:GFjtOC9GE3op9NRQr7a6MQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: outline-secret-key
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVG1iUmZlZGE1eVErNUo3
            OUFZN3pEcnNjYkZCeWxadWthaGtCOTlzN2hnCkdrUTZtaUJ4anNGQzBoM1N2aE1B
            U1AzTytFV3E0eHQ5UHJhWnprMkJxL2cKLS0tIHJoS1ZMd1RaTnB2RXhPUCtQOG85
            UzRoWFdiYkRocUVSQ0NRbHBUYnVwVXcKByxDxXpV6Bng2dQVc+m6FLRlynD5Dipw
            3r5qiTBb7kWwUgQnVQ2DqQtKjcwmSpXXKwTwfkrnteLikEUuBt3V1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:Dua1XmlETPOAU4HqLiK/pc9gh8xwOS3sl9I79UoqGbOHQmRSUkLcKhosf/j0/ck2OQ19Ueli/2HIOQbniy0am7zC3TW+5p9aQeyvYU6KdtwQd5GiCxYSG/nRf5f4VZXnn7ZgkQZ2+rxEu3yOCHYOqShN8njl6ngtyQAGQiZ8HU4=,iv:ziosvtw1BM6WqUK1gaxZ4t/+SddhijT+mTNo9RhVC7k=,tag:UZSO0aZzSx3ZV8GP7V680Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
