apiVersion: v1
data:
    key: ENC[AES256_GCM,data:l5Ylb85ZWvl1Um8sOKzNaccU4ghbv61dCEgenttEFOS4u42wj755GtRIYdb1hJCqqkQ7xz+r9KNi3E3k3HdBye3ylBeSbaZe3mLD7Wjn+bIT5OrvXuFf26V6ea5rRBDyuHcjL7jY3BFIh2N8Cw3qhgNRuPUvXVv2vp4pT8sulTUnRvI7yyl079n2O0ylZ9rUFScjqF1uiXXccYm38aqBjdxivA4IcH0XpRg8dQ==,iv:3+KTX2E/+DbDFKw20Y7jPq42X9jeYrsFbl/ft01Cxs8=,tag:N4E3DU9A4Bsn//UgveEaSQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: outline-utils-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdUhUdytlQjJuVnJvSnJ4
            L0JDOFJYTlgrTTZONnFLS2gvcDVtR0wwdkhVCi9NSWlYYU4zVklCakwyNkg3WmM5
            dWVoQkFnemd2Zm91c0VZTWh6d2ZKLzQKLS0tIDJCS0xqRGl3SmN2MnRWbWtiSG5i
            aUdGVWx6Z2pYeDQwa0hMZlBnWlhtTFkKk1l9n26uPZFVZBcn5ss5mNUQKtAGPhLG
            YqJTAYNdzFLKGq2rncshr37FVT0UYgkOAtYXqiLGaS+PqSt8qnLJdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:9YEkhwzPHHd2Wl8uFQ5x0QJIK6jetxRszKr0/7RCWOC+rtFl6NqmB2sTb+OzvxT1hk7l4tcWaguHS/4C8wWTJPk+/n1nXDAHro2ULjzh+749i2zQmH19eol18MqD8kNo3kwS5/i+DsPjStEmeRX/oIwUlmS0JFazV6vWejYr/Yo=,iv:W/rVJ2RUETKkgQl6jB+SdG4jxxb3xl4MQDKwbzbRQm8=,tag://DOxOgb5z6bc+b97Gh4uQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
