apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wV4uf7tOjTz3Or1ffUmjdK9IXHPN8aae10+aonPFZPdKttMrIVJpsJM3n80=,iv:d4FQtRBlXEmrR01s3934eWF7GYTWv/b7raEN0obfFfc=,tag:RDSpfVfhS4E7aIi6wjfFng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: paperless-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY0VkQmhHcFU5M3R2Qmdm
            c0dDaEF3NXRIVnUySHRpVTJmK21FT2ordkZ3CkRtZFZBNUYwYXFHT1M0Ly8xejNr
            YUFhd09BWUxMeHJ1Y2dPdXprWDFJancKLS0tIGhnRUMxMnZWYjVScithbWZHQmNF
            cGszTGdETFBRNEhaa3R1RWFxWC9qMncKdA3RoZfOKMqL2JvuZ5WLAG/FG+IfosOs
            Sdl95mH9uxbrhXRQSGnALrfqQi+Ygb5GBAG804cW70buKylyfF7g6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:GN69xui+HRKqnUFuXlSesHpgLJSQTfdxM5+kBlz57mnV4negHC+wzIsyNimUeQ1ysHIRa8ll9xkM9XLInMBjSmVpXSQpkDFAvwEoTh1Bd3/EsOt+926O0EUEkT4TYVBRh+vbeJbRxp3eDY0mjq5iUFUT5dqGLwoSKf3hfE4BkWQ=,iv:8kVs7HWfdnTBRxIip7TrTSeoSU+CvIeBoEk/azwbesc=,tag:88/w9fsHSQBD0+iujoFUEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
