apiVersion: v1
data:
    password: ENC[AES256_GCM,data:syB7jWCx+MODrqtLqIIzVpd6irTpA8AIbGGU+Ehh40/nndI3Oo8c7uuh+Gg=,iv:AYqHjv7ajZW04kd8PtzjGMtNIU4hziNWDowRBEm8NbU=,tag:q7PCsQMJ41WR5GFocTybaw==,type:str]
    secret-key: ENC[AES256_GCM,data:h7Emotah0M1utr0mgFo7ZSsLpapQaghaHjZAkS7dSf15PSofpiBVeUDJ2+NAyK/+GhLU/kAtpp9vfZiJ6HZIbc7N8/n7BqbF//rEv4gMPlHk8fBs8/fvEa2MG20aWgH/QpOmsbzVLNicgmygIBywgnOXB5t60Id6BRl24VQ1jWJlCFdE1FlKe1uObY6cqmEFv5oIDF1L6VeMpYyYcjt07RQNerHExU7EE0iKsg==,iv:fExEeRYkoTvi8nYQ2fHl2txA3fwcqCuc2FUhDgR7SAM=,tag:uwIUW82vnHVszsWghcLNGQ==,type:str]
    username: ENC[AES256_GCM,data:Pda8mqfzHO0=,iv:Wxz3zxXi3WIxdgJF450lX9ECww950A2M1Cg+z3cCSsY=,tag:cSJbd8YSqhzbJiTHiIrAlQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: paperless-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TTIrNEErR3dGMUZhazJw
            bnFxZXZRZnVzM2U3TThxNlJmeFFsWCtoZGdjClpFcnVrZFVERHZjZHN3anlHYzVL
            NzZURFB4Njc5cG9nYWx4U3FIUWRSWEEKLS0tIFY1eXJCZGovUWxYRUgvV0VHajBF
            UVpPNzNmMWVCNXoyRy9rZTEybTQ5c2cKARhtnM+pX5mAuJhN4f/35OMeOlGwdnw4
            1UJOccbWDeC3P2NBVNTnrPEChSb2jddGNcN6FJBeXE78kZ7ka5MtkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:MoiaWhaRNjA1IjOfzUu1GW+kOMeGMo4HWhk2H/hA3tg8CSELyWqa9S3VGC1xUgktlY+FYW38k7IdoGnSDnujrR0RI6tFdme75KM3OdPuuwNgDpCetWuS3BswPj9y03HlrIWu8OSZb3Zbn657oiNvUVwRYaLg1NLZZtuGR12CJ74=,iv:/qtR/GW/n6G/tar7ISCvfKOGb6U5zaSdTh6vPUhKvoQ=,tag:h6ZgMudTEEWVlSWmjN5CzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
