apiVersion: v1
data:
    dns-servers: ENC[AES256_GCM,data:EATQIzoIGpK+bKMDLz5zkTDmVmw=,iv:FAAwfASec+AFsHR8dZ3VQ1OzOpqDx5XZpntuQny5rYg=,tag:JpSDUUY/p8S5HpwtTpajJQ==,type:str]
    web-password: ENC[AES256_GCM,data:Okmmk0xfLkCXctOBwPxZAt9jnmSM9vB5e0tKLEv+7Lq//Fin8OVHaHUcU0Q=,iv:3LrW6DUJHIUCKNe7hnKX+emfs94DBkztEtAnIhc4dR4=,tag:WHUlUAbCIvi1Y5FaG/lOVA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVjFndW1YTWs0MElJSHk3
            N2JvVDE4NHhkTXdGUnRvbXhnTG9PUnRxV2xJCit2ZjlyQjVRVDZYK3hLcGdyUldC
            WmVPKytFUllNTi9SVlRRakxXdWFmcTQKLS0tIDJrcmRxT0VKTEgwczQ0MXpkZWJz
            dG5VaVRWbmlFVFdPaXU4cnA0YktYV2cK7GjWO6jPNr/aIejTetrVCAgSIbKHQNGy
            XzHs4rLa7YZz16QDnk3ciIC7tjmn7dYnzTRTDCm1tejOanY/0YZnzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:mqlaPMsSEknKSPZgzQClZ0wScOlHyG1s/LKEQwVjM2kq8gghTzx15nKxZoRyK6F0FfDp8g8R3xATU6nMg1tZELEZA4htfaMiH/o8JjtjaDtQmuazxlsUfy3VXFQPbDeJTh484qOOWbpGIK95WDGPfbssDpHKsLpPOiVKERXvxQI=,iv:cINV1KkuJoJvGQ506FGLMACowfYlt9iBr9lBbtFbxaE=,tag:mmHfyiUtHs9XSrZRlj060A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
