apiVersion: v1
data:
    password: ENC[AES256_GCM,data:1U1vqaRTotpyha3B/uW0knRETRV5Fy6x65uWQSkA1hKbK5NBlQIO3m/GxEE=,iv:tF8wATz+SUc41RwC+cnJSxR9bnF/mAfRSHuH16BSzzE=,tag:iioeE9xV475GYbQ8X9coIg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-db-root-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUTNSSkQ0OGQrVzFOZ0Na
            MWE3UTduS1RYMlVSbmJoRWRYSk9RWWMyMlFjClBUU3hzZ0kwcVNwNDVaRlFlcVNG
            SnB4dy9laTFma1dLZzBXV2xDcG9jUmcKLS0tIDBlWEQwT09IWStiL05IWmt4SVV0
            Umx2VDdidHZyREtxOHZoNXdUYW5nSXcKOrEkXqQmvu7bBmdYbh/KmZXeEO0OfOdJ
            2h/esR6y3S47orBlvtuDSzWzrJdCh0FZjgjNeCSrbgbSwQoBkbpwNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:EzR045Dd4IaDbnTtHJ9wvPrC/mFvDOQUWYDp32WV2a6kBB1ENWl/jlh8+TKGr0fp5NKe8U+xrzn9JYZfLLzWfrfGNn8AO7ftKvUFHG7PlkncPDUeM7C0j9Jp7vXrYv5OQ9AefsLlIUh85ZnLwdCBsoUi1e4+LhspgE5WmXk4Lgw=,iv:oQFumLX+K/HPsHJFg7vVb9r88c7xqi+2r8zQIP0eqJY=,tag:t7QoWAY2Lr1BTUsu4FXHWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
