apiVersion: v1
data:
    secret: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-igdb-client-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSEYzejNhRVYwVXpiaDhB
            NytDdVc5bGZKWE1OaEJndmthNUpwQjFIU2dNCkJqbmlidkpJeEE0cndoRFdDczdy
            dlRocUZOSVZMQnd6cEtxRUdzTzMvQ2sKLS0tIDExSXZwZTZ0LzZGZHBQTHVlTWZO
            NWRZMllJc1lsWDVROEl3aG1reEs5ZU0K1F6uj0Rf52UbYWk3cOo3kj52IYGhQR2M
            p4DhGEeUBR7u5GaQ9B7cywwabRsPHwTLIi7v8+4seRdw9slz55d6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:iOFgtSVsyJUZ3CxQusf3Ma9/VEC7hOVdaX90LKX0w1tVpKnNB3V7uZBCCkD5wz0sUhvqHdusfq40V3Ol+JP+gi3ikFRon9vhNiLe5qal35darFsrvSItYD48T6bZVjpqzkt9ni85jTU2V7su6MRkSAJmS3S4nCqkmornoDhzpes=,iv:M74Ks4NQZ/GRdEZD0q2Egyy7XVsm7qXWHp+iBGTHMcM=,tag:Jv6f/oiLG3JtBr2BFPcwnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
