apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KR2YwHNWzKD9w9ZcskJGLqbdlznJoh9JnM3ySNWwqhBUdrxTXMji+hWBN8w=,iv:wfDg5CUzG0Z0RXsn99NmCqxkNqc+DCR3uDzQ0BgbTlo=,tag:WGRWH5xgf2Vay8QwoB4MPg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRnJqbXFHZ1BjWlcwY2hV
            UElkVVQ0em0yL1ZIdWJtZlNiZzFVMURrZGtnCjFSMnkxVndMSTJaUXZ4Q3AvVllD
            NEMzWVJ4bDdKQlFsbjdycjFIazd2SFEKLS0tIGJyS2lXVExiM1JyQmJidlVXVWIx
            VmpMZXlSbTRWS0k5OGJPbjM2a09sd3cKGwQGTpKMQzOCpWFm0nDL/o/vKBxWNywt
            AtaL9ABNgrXLk00HlGBbkryiuydT1hdVHC3hFPrYpIjHy9SMp2qKxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:U4U2nm9/8YJWndLRXltC3ojLXhFqI+4thyu8RmQmmYPkDblQ8ngPT6ObRG1u9GrHpnlBSSA9juSYfT5uuQv+j45tNijpvyfTtB0/tWYJBrjZbjkrT2ZOz3RQK6V+LEu1kCoBmVhciIICzkyPmG15lifHO2GXI+h7ODV6jUEZg7E=,iv:h6J3jizG+90bvirZ3c4kke6wOLoNdX15q0yF/btaCwA=,tag:wsek09AeRFXjaYtgkH5BrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
