apiVersion: v1
data:
    id: ""
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-igdb-client-id
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraXVRUGkzZ3R1UE4yVFht
            N3NiYnJXbW04UktzV2o2cmh3RWIrbG5rdm53CjJDaGYrMDZ1LzZYa1Q2Z0NEVDdt
            MDVRWUk5S1pRSEdveERJUWRyUERRNGsKLS0tIDU0K3VUTzhmSkpvYTVTMm9pVGQ4
            OEc2cDFOZVFuMUNDdHRRbUM2ZjhtMGsKrDdLGvfDcIto0X8w1P37hFA8O26xSHap
            twpY1J89jqMSDWw7acLZ5VFfssB5QpAnsd7nJanWQWa2a6pkcEdiwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:Crcx7dqGv14D7KzP++rf+meRrzui3TegBAeWRD8hKVpp9VOJf0+QKwX4HUlb+U8NNgEgYoyzIFxtSYK/j1qgrBK2/SEZgbOiX4KuB0+i88lN/CyUSUzxoX/SJDnJ9u/LEGJo2ae3j8yd1KfawdTXsP9VtmhdsMM4DAh8D6hzBuE=,iv:OKV45N7BwbmvKw1a+phyadl2lUSyIN+3btLtL7QgPps=,tag:VLY2Ke9PLpv1ur8TIk1v0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
