apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:pQ4vxuNXLd08ckBQAa9xtgPXT8ioa+bqJ4ZX/ahVho/Wn6dhhcZWDiI1NXpS9MAwDKslXe20HMw8LsE0le1C6qKI0z/9XZ4eJF93QkTU0nBN/6H+7z7QaMYjNiOmmcZPnJd5lxOWDBQNP/I83m57yj9L6X+YYfe1AjOxziM/LhF8sz0TBlC+Ci+/kbmaO1yJYpkp62jd5rR79yr0X/cm72j+AGN9cm4pHAf7Eg==,iv:S6KE0JbIHn/CpkZ0iD21Rgh9BGOuwpJQnoYRKKgIzpk=,tag:2/iI6KqqqleG27o6CNbNSA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: romm-auth-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLczBxVm52OGR2enhDRHpY
            UEpodnJCcytqTFViamFvUkNETXpFNkQrMVYwCmo0a2tNMzVxdGMyRE1mcmNRSTA4
            UktlanNDQ2ZkTUJLZUswVzRGUHo1amsKLS0tIGlPWWZ4bW9yYUt1SkVMREdOb0tp
            djlLTDk5WndJU3NWZVBTWkdRcXU4djQK6q+4359EI5MwVIobssZIbvLts5zcPuN6
            23kPozGGcmYDDY7NFeHVOb5sjmFMW+Drkuxk6lA1Z0Fz1KIHdLJ2iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:VUkaAioxSWemKGCbXVWMwact7bTIjPdc+IEBqEXh64/aiZ+113P8TWhPppfX6L/AdcmrPRTQfwyKYF34dVMj8UqMzlE3IfQo/iZ0gwmbuc2UO/VCPtHIBGTVYwv1ruDoCvkVZK2+u8+qRBjLGfTFijZ73b/miz227+L4AknxbbY=,iv:6PnlyUzbeqtTRqSKpirir+n4hScmmtgrqbCT2v6iljE=,tag:JcNAKKJCwQLzFpIjem0a5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
