apiVersion: v1
data:
    instance-name: ENC[AES256_GCM,data:mPWguTnwPq447oXwDOk7d/baB5c=,iv:/svxpB7q1Sg2wz67ctqM/c7vgFc3lkfeJX1rmnQvnlw=,tag:+2qaqxe+aBRwAIT9Dz3yiA==,type:str]
    secret-key: ENC[AES256_GCM,data:f18Mpd4/UN75ISRAw3TJuOWUoYZ4SJiptwRo32F97cs23UrgmUlf/YjxBaTY09cm8vSSr7w1fnVFJ0qiJlbmaT3/ZCKUBIXxA1+WNEjOJdiI0soFeIo24aP4mS2JrTJv2JbwMqmJJT3eT4GwV7VDxRH9ERi+GlWwrpor2rj0LAL4L6/gI8i8z4y5AwObdOf50wWYXEGgTRXjlto+1hLnnJhZJYqomSipSeL5UA==,iv:9vCD5tpXGV06MUid59b0N303U3TCEYpi4fHCDoEHelw=,tag:ZIBkCL5Q+5gNsosg22GlSQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: searxng-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVmhpYi9CNnFGU3NHdGpi
            YmtkcEV0dC9hUk9tK0loQnJVRGVEbloxZ3hBClRsQThJOFo3S2lxSlZaUWlFWlVz
            VTRIaVpnMms4SzQ0ZnZVdVdjVVJST2MKLS0tIGdjeUhwN2U1NncwaEF6b2Z2ei9j
            SjNmb1AyVm1iMFdncGhCYlNZN1J4UmMKZ2zE8eBRPA8/oskZZzpqGvT+jm6NQom/
            1FWbvjmPnSzIEb1WHcoonSVeuG+UZUS3if5Q4LF64TDU+vECDOY2jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:2Vrk0gGWDT0cB5PDDX8d5ZysPA+B6qh3zNRvXNaUaGXOiD7Ync3aLin6YYt3kICYHIv30SUGF3AlyAqDSimwuMzxqEKpvE8jpUGm5kSZB2fcLwyK/pK92RuRHw8PMDG54Sr4MnXA3l5lKB+r+pe+HzNKgXf6Fe998InJwwkVJCo=,iv:4InqS6+5JalrU5Mp0QrQ+MxKcXnP2lZ89vwVX93tujU=,tag:+fRFcmAICh7Ckwjqb/OOZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
