apiVersion: v1
data:
    form-secret: ENC[AES256_GCM,data:eVRJC3+xnXcgICtFp9tkIOhvr5bTaMujiC50Kj0ivsFDIT5R2swsS42JuwCkRBWlnW1NkdzIQ62el/ArSMIKcC20RUjm9mCxGifMA3voz2U/xWXvfyOlfrybz9z2JgI5S8cPALXBgSh0pnc0uwZGTsvbqNgzjyEIz1MYtlXXo71lib8133dEx1gK5C24TUy8xOrzaBHxTkuOIyUlpgeX3j40+adkyZ2cuZETGA==,iv:BNpNX386zIDWUpx7+rMVhwDg0vI8t+W5tbjp2iwBGNg=,tag:HkHPPM/xzLptNmbg8c9dwQ==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:bkeXeKKArDTXWC8E73kymXyXyhSsI8CaBLX90KGhYhK+PqHRN7UEOU2TsmMmy090bXso6EfPwjV3ybPeebyuhrOj6FC9oLLTOV0xZciTXo1O9l/EDcWPRySu9LZTYgYH/N8R9cFpcj9H+FNTR9UHToYKnC/7fthP+YIrn92UCmjnKsza65wjwuGe/x9wzTuXKr+/Ru8kjj1h3Bp/vGMCZVA8zkO1NLq6MEO5MQ==,iv:egCJv7IU1ESMuhykDhOnU5h9U2Bbbd5G3EkLV5xY5oI=,tag:W71lNrZ+ErwKCaHuakGZ2w==,type:str]
    secret: ENC[AES256_GCM,data:D9cJFtPERsiLAfbS3NyDfdaEQhYRN9W9Kz7wlX1yw/fAvbio+0js8tKy0Mvwcydt4nrZ/TKirN6evBCt7i/+OI20bVrsNVtn7ZGhxQke1cTHqxiZcPbinpS7eBN4bvFRntrF9+ePV+GYproOaM3pUpuJj47WZ6E0lH27f4yQvO4jsLkB6jqpNqlCtDredsKOGjQsEPxhOZc71+Ifsalo4zfZjCqcuwT8VsuJcA==,iv:hS0STlDhV501FGCDTmJ6PxF8GfUM0FqqyQxQo9eUlAw=,tag:7I/hEr2hBIRZwlmaDyNE6g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: synapse-registration-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVWhrV0t0aSs2MWNKclBK
            Z0FrYjd2MlNuTTRlSTlkM0ZoVjdvbzBPWkc0CktseExrMklBRTZLTWU1T2JDQ1B0
            cHRYalJObzVyOVV0TTZxSEtnUE95SkEKLS0tIFRXTFM1OTNzOE9OSDVjcDdqRW1Z
            UnhPU3FTeHI2M3Y3aXBpQlFWNjR0WkkKO73auPtMnFJirkXUHcMMDE4zLydgre23
            vwrBGzrklviH4sm6q4Fl197T3Lacp3PjGUdZFQ8RRjyNR+5mEYgcJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:nIvoRwAmT/RMa144Q81GfD3jM4r9oMaExsLy59gI0M6mIBOQJv4Yn0rO1gb2668gjLynsUoZdidrIznzRjgbq8rYnS+ypbYwupu30jwR2L2NUORs+7VMi8caz6/b+N+xXB20ypurESWARIjuMekMYUTIsRH6TVyhNp4XMlq4W8o=,iv:f9PYuhT3ZAOpTYaLdALRtcVvBBpwKXDJNevuW1fEBp0=,tag:KiovZccIXPnSBkypAXLw8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
