apiVersion: v1
data:
    password: ENC[AES256_GCM,data:L37GdgOQl5nu2S/gV3Slvw9jGtpX5pln4l0wPWFt2Zp2nKg4q/UHYqxkXQc=,iv:nJEP+uUu1JWXv79ErqSwGlIMz/TLPOCf4CAFomqEIIo=,tag:47SN/X5eMseOMxe5dxH95A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: synapse-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWnRGa25CQnp5dFBINmxU
            N1JzNVB4WUdOdTRUYS8wK1Z0cFY0QWJTWUU4CnVvN1pCWnIvRTBwdnRXTUNMTVph
            N250dHpCTGlwd0JEL2s0NXlnWmRCc2sKLS0tIDVGaWJUSWxUWEpBeG1URGU3WGYz
            THUvTytLcVdxUWhqa245Y2VXK2lqWkUKjMTwk2VqJJw8f+Gu2yq3aAAzNZM8u8Z+
            Axh3by6JAhBdkDvnYvl5EFBA3RCqnFH7KTq483Q89Qsh5vjQi4THdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:cdnroc5h9Lm3SyLyYGSw0xZni5J+x9hplLPIVVVYKUNMqUYj0M4oZs3a0mWdkmawx6/Ol2N1VUUY4PayDfgtHQYcsN5XXlfFKudL3qB5ZE20VLZXTd0PhmyafJxtRRnvmaqPEq2hLBnTND7EUQwUdL8qteNqD5/Tgj5oLVT/VEk=,iv:9CcYxuLrSVYN6BWamTdRFImfT0/kr2K1H+f6BCeMHMQ=,tag:413RdZKAeqqALcfaOSXjzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
