apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:mbrCEX8HU1FbbpqpafoMzmsEthxdPq46e8eWl5fv48JkV+R+XFK3UrGXJCM9B5Q/JhX95IzbLTsF0VWt3w9XSFHjWMFjGNA6LDW7o1g/xd6kYBvk2VcNaEyplqIhpKZXsqDXQwSiDhknNEg16spr1TFpH/wkKrFHecMr4x//n+yU5MkwHIbCfRrRg2lcs6GytOCPgc6KNtTrUGz5aH+1iHa7et2PsBBI4fkT/A==,iv:qxIdEv+cPgZslfcOieIUXDV4FCBx4rY6D1f1kvXvMog=,tag:fr1saVl4bB1I1aKfx/V0ag==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: umami-app-secret
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWk1HeGtWTjRSZ1BITDJi
            RUVGWjBQejJLc2hBOHFGa3BMa2ZtdWd3M1dFCmQ5MiswUDgwUDZVQ3RoWXZkRXBr
            eTRleGo4OGdUc05ySFM5UmJPZ050dUEKLS0tIHBMOFRJZ1dBZE9LdVFZbG1hYlhk
            NnV0K2w0QytGMUpJbmozRjVTZDl3d2sKRjoQI6JlnNhZOb1inxD2IGgbm/v80ut3
            6WVslgcakgSc5pj3H4dTIVdXkQDKagIH8BAs7gW1NG55tcBdDt4mpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:44Z"
    mac: ENC[AES256_GCM,data:BHpaGac7G4ITXYVzNegiKary6WLJue9DUujHqD5qogHVRE4x4OQeVWeUmjAqGFnEPzckvujppwU1gINa7UFiv6b8ueNdcpTci+VqVjoEbAskJUyyuxQnTLT82n2pn0OKSgh46iJoRHG9ad1bljkwhMQeb1mtXlTQxIeRUG8AztY=,iv:YYQjltoBsgvGz8RquR8l3A680DrXpupMgXr671odX7M=,tag:3MBbzTJIeoevHS4Cdi+i3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
