apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3aH2Cy+4Sg8tvToaNCpSK/zbtNzxdctOQAiX9pDzO0g40SU2p5RVav/uHO0=,iv:W09W2MsveXpZGTPC8tA2vYCXx0wpHZyWsj8x9qhUwKA=,tag:wEENt2UAR3rx6BAN7PO6tg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: umami-db-password
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQk1TSDhKZk93cnlZRTha
            bjBqZkJBQzJOd21PdHdadmcyeXpTTnNwT1M0CmNDb3pHWTVyVkdFMUF6NUxEWjNp
            MGdXc1NyOUNScktHQnhzdkh4ZENvODAKLS0tIFQxTGd2RkFkY0JmNjRNbTNVYkJ6
            Yk1EWWNHQ0VHNlVMT2phd1lXNlIxdFUKY7z95J4Srl79tujO8D5aWPp9OGNhHLRt
            InzlJaMK1hr9duSLkeI309DSZcpFbv7xSpXmVrDS4a/60ZTctuAQSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:KLTHBViuqA3n3RUpytkIVaAUA9Gf23l6U/PcQuC7Ks12ChxoIX97EHFTpc9xVR1TKClJqqYyp7w6pzh3d4XvYE0MHNraymiYOKy/nt4UueThbfOfrTIFJZlniMcyzM2XXQ5tZLO83qgnm+JUjnfrC0dyn/AcKHduBrFMz1FQRZQ=,iv:ZDbM+13eI/K2Va3bg8faan1bvG3ejFi8+4WrJBEZ4fE=,tag:jOPxD+KIOL3S+fgrr+N09Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
