apiVersion: v1
data:
    admin-token: ENC[AES256_GCM,data:4WAzim8ZReiZeNhNcu/dJedTMIgtFBZvPr33OEjj7fAt4PkkK2uqEjLO3tfV+er93e8RRxGLinCNRZVsXlgDF59/N0lSVdP703SWPpeUY/DBMyM9A4zXAyRsihJnNQ8IYK7JDBcr1NPp1nXdW9knDJUv4WL6R5MinTiqYV60/B6nFAmy0SozTjN8dzIbi76mG+/9yDJVMBdWU9q6fcmkx1HlEEjddZkhwmfLyg==,iv:xB7mjw98kcQL2gYNojOvCTBNCHT+Ubl65Pr5U1TWAAo=,tag:DlKVZDF54qCMt0JSc7+mkg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vaultwarden-admin
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c25HcVBRQWs3ZDJNVWRR
            cUtyT2c1VVpMeFh3ZTF0ZVdpbjYySk5LRkg0CjcwTVg3TWp6Q2dpZWI3OFBaSUVs
            amhkMnNwL3ZDWHZoSkJBOW5QNkcrTWMKLS0tIGM5azdvV1BLWTlXZlFWTUY4VW1z
            TjZCSHBNeWFSQWh6NHVvRnhXTlRCMDgK/jYEw9Klog3wObCF0JUm53wKBzW9J0zJ
            0exCSusNWjnnnEHq9WB6lMmWrKolJ4/g37wFV8uujbsiSUWLDYjQNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:Um8I6uAbkoNtMfD8jBCV6rPJeWd/lviRuvdiIMaQyjYl0XtxsPe02AUTNDr3ZKcknnWniA1bV+gfm2UBrXEXtjGBwSrg2JTSjK3ML3m8moUM8mnZIgivyD09G1LdfSRVsp5opCx6opFa68JNqNkX10pYhgfWeLrMtmCEe05r+Us=,iv:bbEHplM0LnAt7iOAOKoNYvcLu93BiXwWe9cvXd5N9Gk=,tag:x5HBvcyEUFt82/eIo5sejQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
