apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:ddyX30rDCu8=,iv:PRvfQbi6FkMcKaIZmmYDqVVCKLHz/kzYEfqOk4wdthU=,tag:op3ya7EYc3Lu0QnUYWaG5A==,type:str]
    secret-key: ENC[AES256_GCM,data:u9sKhVnRvZEyRGp3/F1PhyNQEpbKrAIrCDdy12T/lS8h5eXxxiuDEFMc8BwY8AiVI3Yx/EzXCb147BKMVrUKljjWfiemuaB5pGxnqLk26DOIwNWptT6WCw==,iv:XxQ//YbFWri1QS7aUQbylDD5QFsCbVYOxMDw/y8Q1uY=,tag:Iu+ss0H7R4GDlPPKn/blkQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: velero-minio-credentials
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mk40dG1zYXhMaDFjdmh4
            cmx3Y2JITVFaS2x5WFdnNEl2Y1VyblE1QVJjClB2MERvL01WYnhvVTc4dWlPVE1m
            MVJNeVo0UG1idmw3SzFKSE1MNEFmNW8KLS0tIDdaUHE4WlhXOUlINjNmTy9OSlFk
            ZDJuRUEwS1VRcy84TXc5L0dYbHo2VzAKQdKGi9F59xVfeoKWCRRFzymjNNuaeEgH
            ilFgv0Lswfy2A620jLgYzRinDbzKcYXNW6AXI5ZTZqL38BwBPGf/ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:42Z"
    mac: ENC[AES256_GCM,data:aChUT9psXh50Z83Gqe/ozuL6jsh8adhHmwbZ/5tFUNldPApz/MlMW42GC2iOCBLDuAzBkaoCtHn4wfkLyh42Jr31M0+GANkD8XsgUBfloe3AnDa0CUttyATUA31ALzoTe2yhnRHN222ho2wgYJbR3Ae0cI4TWDRhai3bJ4D6ilQ=,iv:xq+No4IK1aa8CB3Jl+wT4h1dYkLeTkvh6K58kuFXZtk=,tag:G64qzgBffMZvC9mIxWzJdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
