apiVersion: v1
data:
    internal-subnet: ENC[AES256_GCM,data:nnTrXojegecy3sLL7dgtxA==,iv:Ees8/RSqeizqUUvglviF6oSe0aN/jraN4eU8y9eJJg8=,tag:FV061B2CDEPiZpbN2GpnZg==,type:str]
    ui-password: ENC[AES256_GCM,data:+UL9EFO521ZQjz+Y9Cpc3oX39AP02HwugvoDVjbcTji1wEt61JAZtcizGWk=,iv:lBM/0lEweKdq4gVTe7ycYeSYV1Od6SRuMNvwDynoMjA=,tag:+UHdsfNv39roHW43UB+W6A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wireguard-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdlVQYUc5NVVTTmdUNjdp
            ZjFQNWl1ZFROVGZpNUFIRForeURZeG9KcFZJClhOSm5BaUUxMzZBMkhGdzdaTWpS
            S1dQU3FPSWUzR1dXWjE0b1h6RzVWaUUKLS0tIEFUcjZOemJTSnNHaHR2WittQWVS
            aWx2ZWx1VXRna2hla3IrNlFKTFFGR0kKX0vxo6Xq0ZHHrtyoQDX2rrr+GmWoQ+N1
            FO6KUlNq5syfV/SFKHwBkXy+ffOQU7yDuiBTt3BB1e5jdsCpRw7Gyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:eVXCSwzm4ZviPvwMFrMCW3yKMiGIx/93RHWgz50aAm0rjDl0/2G+YijysVq2hpkwxwP4xrFEOUfkdfP4zI59BYAD7wJaoq+aMdPHMBVYLHVHvv4ALNJshRsWSWfysS77kMs/djhvABH9KmDv0gCcl5F37q7xoyxbBtHKbbj6S2Y=,iv:5MG0WwbBYMK6j7SOwGm6TNkbckYfX4AUEdxQbILlOYM=,tag:ep777lUxzvPMFz7Z8P9skA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
