apiVersion: v1
data:
    auth-credentials: ENC[AES256_GCM,data:M936X1zQ3zLAHoFgjXkb7C4dsL1KydhJiDaVEhmzP+cE4sWlWHMJ0Yi5ZU9BCelZBJ72ig==,iv:lNkqhd4JEZP5k9aKyJDJxymI7WgFMUgWT5+m+PPhg2I=,tag:Qi4R5hPIyW9xYOfTqUzamQ==,type:str]
    auth-password: ENC[AES256_GCM,data:GFGqIeA2tW7sDYzLMckmEllPGB3tEGkJiyiL00mm1+9ATk7ta3eCdILnSdE=,iv:L5QSUiHGGcL7giDg2MR/aThixJcbo70xVLL/ni5mM3g=,tag:3hKv6BXDTA8BnD5a8LUkYw==,type:str]
    auth-user: ENC[AES256_GCM,data:oI22TnCiNrY=,iv:Qga7SgPIc1iNNCAlJrxyzbhEHDSIKml/RLgClTHrKSE=,tag:qyKIxi2EPFLguTznhP825g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: yarr-config
    namespace: secrets
sops:
    age:
        - recipient: age1k2al72x2mm49jwetctk3t2u3arhhr3t28rv8pvdjzeq6ukjq6clsz7rlt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWDI5OWdyNWxUbVcxTFFQ
            U05wRXd5TG5HSjZlcnhqcFFtNFJGNlJlSkdvCklQYmNnWDlrR01Md0NvcjgwOEQ0
            Z0NONnhmVzhaRTNGOFBMNENlZEtKTFkKLS0tIHducytvaXFrSlhFU1lhK3g0WGZL
            Mjc3THNKaEtIdzVOM1ZvUzBXdFN1RFUKOMvTsb0dz5JVJScO/RN0UQZqq9IlbuAz
            XWdV1VlpEytuXi8L5Wv4SP35y1/QTJvWsodwXNVWMQ+uihpGcOJI/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:32:43Z"
    mac: ENC[AES256_GCM,data:PlxPhhjRQ5bzJGHHNJ+7oQQ0vcF8dIZD6n7A+iMrjh2cXHSb13K2Sep9OOmYaQhGuqKPT70mFTiP1YwxhXhoMSUP3UFqNSXVcO/XMRFvQHqI53/pwExEgorZUmuEjlQGqXTz+0gAqARbZsYrB6Sy6/I0cjhYCvIljEqWnZiu0YQ=,iv:U7Ca7xh2NsC8LHCpXQcT70KL0qijkDnjRH/7D+40SaU=,tag:24GklW7Uc18Q9C5GznF/kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
