---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: searxng
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    persistentvolumeclaims: "3"
    requests.storage: 5Gi
    pods: "5"
