---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: laya
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 3Gi
    limits.cpu: "3"
    limits.memory: 6Gi
    persistentvolumeclaims: "2"
    requests.storage: 10Gi
    pods: "3"
