#!/bin/bash
# shellcheck shell=bash
#
# GitOps manifest generation: the ArgoCD app-of-apps, from the catalogue.
#
# The imperative installer and the GitOps path must never list different
# services, so both read the same descriptors. This module is the one place
# that turns a descriptor into ArgoCD objects: an Application per service
# (split default / optional), and the AppProjects whose destinations follow
# the services' namespaces. Its output is generated and checked in under
# kubernetes/gitops/argocd/; nothing here is edited by hand.
#
# Interface:
#   services_argocd_write     regenerate the checked-in files:
#                             kubernetes/gitops/argocd/projects.yaml and
#                             apps/services/{default,optional}.yaml
#   services_argocd_check     regenerate into a temp dir and diff; returns 1
#                             and prints the diff when the checked-in files
#                             are stale. `./scripts/ci.sh` runs this, via
#                             `./scripts/services.sh argocd --check`.
#
# To regenerate after changing a descriptor:
#   ./scripts/services.sh argocd
#
# The remaining functions (service_argocd_project, service_is_default,
# services_argocd_applications, services_argocd_projects,
# _services_argocd_source) are implementation, not interface: they are
# reachable but not part of what a caller needs to know, and may change
# shape whenever the generated files stay byte-identical.
#
# Seam and depth: the seam sits at the two write/check verbs, so a caller
# never learns the Application or AppProject schema, the sync-wave rule, or
# which files exist. The dependency on the catalogue is strictly one-way --
# this module calls service_field, service_group_field, services_all,
# service_descriptor, _helm_chart_is_local and helm_repo_url; the group's
# defaults and AppProject are columns of SERVICE_GROUPS, not a second list
# kept in step by hand; nothing in the install path in
# scripts/lib/services.sh calls back into here. That is why the installer,
# disaster recovery and the KinD harness never source this file: only
# scripts/services.sh does. Splitting it out keeps the locality of the
# install path (a service is installed) apart from the locality of manifest
# generation (a service is declared to ArgoCD).
#
# Sources nothing itself: like scripts/lib/netpol.sh it requires
# scripts/lib/services.sh (and through it scripts/lib/helm.sh) to be
# sourced first.

if [[ -n "${HOMELAB_ARGOCD_SOURCED:-}" ]]; then
    return 0
fi
HOMELAB_ARGOCD_SOURCED=1

if [[ -z "${HOMELAB_SERVICES_SOURCED:-}" ]]; then
    echo "ERROR: source scripts/lib/services.sh before scripts/lib/argocd.sh" >&2
    exit 1
fi

# The service's AppProject: its descriptor's `project:` when it names one,
# otherwise its group's project column (SERVICE_GROUPS in
# scripts/lib/services.sh). A group with no row falls back to the
# infrastructure project, as an unclassified service always has.
service_argocd_project() {
    local name="$1" explicit project
    explicit="$(service_field "$name" '.project')"
    if [[ -n "$explicit" ]]; then
        echo "$explicit"
        return
    fi
    project="$(service_group_field "$(service_field "$name" '.group')" project)"
    echo "${project:-homelab-infrastructure}"
}

# Installed by default: the group's default is true (SERVICE_GROUPS in
# scripts/lib/services.sh) and the service is not opt-in. This is the same
# default the installer applies when the group's toggle is unset, so the
# generated app-of-apps and a toggle-free ./setup-v2.sh install the same set.
service_is_default() {
    local name="$1"
    [[ "$(service_field "$name" '.optin' false)" != "true" ]] || return 1
    [[ "$(service_group_field "$(service_field "$name" '.group')" default)" == "true" ]]
}

# services_argocd_applications <default|optional>: Application manifests to stdout.
services_argocd_applications() {
    local subset="$1" name ns project prio wave
    echo "---"
    echo "# GENERATED by scripts/services.sh argocd from kubernetes/services/*/service.yaml."
    echo "# Do not edit; change the descriptor and regenerate. CI fails if this is stale."
    echo "# repoURL is replaced by the kustomization's homelab-gitops-config ConfigMap."
    for name in $(services_all); do
        if [[ "$subset" == "default" ]]; then
            service_is_default "$name" || continue
        else
            service_is_default "$name" && continue
        fi
        ns="$(service_field "$name" '.namespace')"
        project="$(service_argocd_project "$name")"
        prio="$(service_field "$name" '.priority' 50)"
        wave=$(( (prio - 50) / 10 ))
        cat <<YAML
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $name
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    homelab.service/group: $(service_field "$name" '.group')
  annotations:
    argocd.argoproj.io/sync-wave: "$wave"
spec:
  project: $project
  source:
YAML
        _services_argocd_source "$name"
        cat <<YAML
  destination:
    server: https://kubernetes.default.svc
    namespace: $ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
YAML
    done
}

# _services_argocd_source <name>: the Application's spec.source body (4-space
# indented). A manifests service is its directory; a kind: helm service is
# its chart (a repo-relative path, or a chart in one of HELM_REPOS) with the
# descriptor's values file.
_services_argocd_source() {
    local name="$1" excludes count i when file
    local kind chart release values version_var
    kind="$(service_field "$name" '.kind' manifests)"
    if [[ "$kind" != "helm" ]]; then
        # Files behind a `when:` toggle are installer-only; ArgoCD never applies them.
        excludes="service.yaml,values.yaml,*.values.yaml"
        count="$(yq -r '.steps | length' "$(service_descriptor "$name")" 2>/dev/null || echo 0)"
        [[ "$count" =~ ^[0-9]+$ ]] || count=0
        for ((i = 0; i < count; i++)); do
            when="$(service_field "$name" ".steps[$i].when")"
            file="$(service_field "$name" ".steps[$i].apply")"
            [[ -n "$when" ]] && excludes+=",$file"
        done
        cat <<YAML
    repoURL: https://github.com/your-username/homelab.git
    targetRevision: HEAD
    path: kubernetes/services/$name
    directory:
      exclude: '{$excludes}'
YAML
        return 0
    fi

    chart="$(service_field "$name" '.chart')"
    release="$(service_field "$name" '.release' "$name")"
    values="$(service_field "$name" '.values')"
    version_var="$(service_field "$name" '.versionVar')"
    if _helm_chart_is_local "$chart"; then
        cat <<YAML
    repoURL: https://github.com/your-username/homelab.git
    targetRevision: HEAD
    path: ${chart#./}
YAML
    else
        cat <<YAML
    repoURL: $(helm_repo_url "${chart%%/*}")
    chart: ${chart#*/}
    targetRevision: ${!version_var:-"*"}
YAML
    fi
    echo "    helm:"
    echo "      releaseName: $release"
    if [[ -n "$values" ]]; then
        # valueFiles are relative to the chart path.
        case "$values" in
            "${chart#./}"/*) echo "      valueFiles: [${values#"${chart#./}"/}]" ;;
            *)               echo "      valueFiles: [$values]" ;;
        esac
    fi
}

# services_argocd_projects: AppProjects whose destinations follow the catalogue.
services_argocd_projects() {
    local project description name extra
    echo "---"
    echo "# GENERATED by scripts/services.sh argocd from kubernetes/services/*/service.yaml."
    echo "# Do not edit; change the descriptor and regenerate. CI fails if this is stale."
    for project in homelab-infrastructure homelab-media homelab-ai homelab-productivity homelab-security; do
        case "$project" in
            homelab-infrastructure) description="Homelab infrastructure components" ;;
            homelab-media)          description="Media and entertainment services" ;;
            homelab-ai)             description="AI/LLM services" ;;
            homelab-productivity)   description="Productivity, content and communication services" ;;
            homelab-security)       description="Security and authentication services" ;;
        esac
        cat <<YAML
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: $project
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  description: $description
  sourceRepos:
  - https://github.com/your-username/homelab.git
  destinations:
YAML
        if [[ "$project" == "homelab-infrastructure" ]]; then
            echo "  - namespace: '*'"
            echo "    server: https://kubernetes.default.svc"
        else
            # Static, non-catalogue namespaces each project also owns.
            case "$project" in
                homelab-security) extra="crowdsec" ;;
                *)                extra="" ;;
            esac
            for name in $extra; do
                echo "  - namespace: $name"
                echo "    server: https://kubernetes.default.svc"
            done
            for name in $(services_all); do
                [[ "$(service_argocd_project "$name")" == "$project" ]] || continue
                echo "  - namespace: $(service_field "$name" '.namespace')"
                echo "    server: https://kubernetes.default.svc"
            done
        fi
        if [[ "$project" == "homelab-infrastructure" ]]; then
            cat <<'YAML'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
YAML
        fi
        cat <<'YAML'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
YAML
    done
}

ARGOCD_DIR="${ARGOCD_DIR:-$HOMELAB_DIR/kubernetes/gitops/argocd}"

# services_argocd_write: regenerate the checked-in GitOps files.
services_argocd_write() {
    mkdir -p "$ARGOCD_DIR/apps/services"
    services_argocd_applications default  > "$ARGOCD_DIR/apps/services/default.yaml"
    services_argocd_applications optional > "$ARGOCD_DIR/apps/services/optional.yaml"
    services_argocd_projects              > "$ARGOCD_DIR/projects.yaml"
}

# services_argocd_check: fail if the checked-in files differ from the catalogue.
services_argocd_check() {
    local tmp rc=0
    tmp="$(mktemp -d "${TMPDIR:-/tmp}/homelab-argocd.XXXXXX")"
    # shellcheck disable=SC2064  # expand now: the path is fixed
    trap "rm -rf '$tmp'" RETURN
    ARGOCD_DIR="$tmp" services_argocd_write
    diff -u "$ARGOCD_DIR/apps/services/default.yaml"  "$tmp/apps/services/default.yaml"  || rc=1
    diff -u "$ARGOCD_DIR/apps/services/optional.yaml" "$tmp/apps/services/optional.yaml" || rc=1
    diff -u "$ARGOCD_DIR/projects.yaml"               "$tmp/projects.yaml"               || rc=1
    if [[ "$rc" -ne 0 ]]; then
        echo "ArgoCD files are stale; run ./scripts/services.sh argocd" >&2
        return 1
    fi
    echo "argocd check: generated files are current"
}
