---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: homelab-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/authelia-admin.sops.yaml
  - secrets/authelia-secrets.sops.yaml
  - secrets/authelia-users.sops.yaml
  - secrets/code-server-password.sops.yaml
  - secrets/crowdsec-config.sops.yaml
  - secrets/drone-config.sops.yaml
  - secrets/gitea-admin.sops.yaml
  - secrets/gitea-db-password.sops.yaml
  - secrets/grafana-admin.sops.yaml
  - secrets/harbor-admin.sops.yaml
  - secrets/harbor-db-password.sops.yaml
  - secrets/home-assistant-token.sops.yaml
  - secrets/hoppscotch-db-password.sops.yaml
  - secrets/hoppscotch-jwt-secret.sops.yaml
  - secrets/hoppscotch-session-secret.sops.yaml
  - secrets/immich-db-password.sops.yaml
  - secrets/keycloak-admin-password.sops.yaml
  - secrets/keycloak-db-password.sops.yaml
  - secrets/linkwarden-config.sops.yaml
  - secrets/linkwarden-db-password.sops.yaml
  - secrets/localai-api-key.sops.yaml
  - secrets/mattermost-db-password.sops.yaml
  - secrets/metabase-db-password.sops.yaml
  - secrets/metabase-encryption-key.sops.yaml
  - secrets/minio-config.sops.yaml
  - secrets/minio-credentials.sops.yaml
  - secrets/mosquitto-password.sops.yaml
  - secrets/mysql-root-password.sops.yaml
  - secrets/n8n-config.sops.yaml
  - secrets/n8n-db-password.sops.yaml
  - secrets/netdata-claim-token.sops.yaml
  - secrets/nextcloud-admin.sops.yaml
  - secrets/nextcloud-db-password.sops.yaml
  - secrets/nocodb-db-password.sops.yaml
  - secrets/nocodb-jwt-secret.sops.yaml
  - secrets/node-red-password.sops.yaml
  - secrets/open-webui-config.sops.yaml
  - secrets/outline-db-password.sops.yaml
  - secrets/outline-secret-key.sops.yaml
  - secrets/outline-utils-secret.sops.yaml
  - secrets/paperless-admin.sops.yaml
  - secrets/paperless-db-password.sops.yaml
  - secrets/pihole-config.sops.yaml
  - secrets/romm-auth-secret.sops.yaml
  - secrets/romm-db-password.sops.yaml
  - secrets/romm-db-root-password.sops.yaml
  - secrets/romm-igdb-client-id.sops.yaml
  - secrets/romm-igdb-client-secret.sops.yaml
  - secrets/searxng-config.sops.yaml
  - secrets/synapse-db-password.sops.yaml
  - secrets/synapse-registration-secret.sops.yaml
  - secrets/umami-app-secret.sops.yaml
  - secrets/umami-db-password.sops.yaml
  - secrets/vaultwarden-admin.sops.yaml
  - secrets/velero-minio-credentials.sops.yaml
  - secrets/wireguard-config.sops.yaml
  - secrets/yarr-config.sops.yaml

