---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: gitea
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "5"
    requests.storage: 50Gi
    pods: "10"
