# Development resource patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
      - name: traefik
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: METRICS_ENABLED
          value: "true"
        - name: DEBUG_MODE
          value: "true"
---
# Development specific configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
data:
  debug.conf: |
    # Development mode configurations
    debug_mode = true
    log_level = debug
    enable_profiling = true
    disable_rate_limiting = true