---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: harbor
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    requests.storage: 200Gi
    pods: "20"
