name: semgrep

on:
  push:
    branches:
      - "**"
  pull_request:

permissions: read-all

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run Semgrep
        run: semgrep scan --config auto --error --sarif --output semgrep.sarif || true
      - name: Upload Semgrep results to GitHub Security
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a
        if: always()
        with:
          sarif_file: semgrep.sarif
